### PR TITLE
#1549: Adjusted download exception type

### LINKED ISSUE #1549: IDEasy omits error messages when a download fails
### Actual behavior

When I try to download vscode I get this error:

```
...
Resolved version pattern * to version 1.105.1
Tool vscode has 0 other tool(s) as dependency
Tool vscode not installed in D:\projects\release-test\software\vscode
Tool vscode not installed in D:\projects\release-test\software\vscode
Resolved version 1.105.1 to version 1.105.1
Could not determine file extension from URL https://update.code.visualstudio.com/1.105.1/win32-x64-archive/stable - guess was zip but may be incorrect.
Trying to download vscode-1.105.1-windows-x64.zip from https://update.code.visualstudio.com/1.105.1/win32-x64-archive/stable
Step 'ide' ended with failure.
Step 'ide (vscode)' failed: com.devonfw.tools.ide.cli.CliException: Download of vscode-1.105.1-windows-x64.zip failed after trying 1 URL(s).
1 step(s) failed out of 2 steps.
Download of vscode-1.105.1-windows-x64.zip failed after trying 1 URL(s).
...
```

### Reproduce

1. Try to install vscode using a proxy

### Expected behavior

Instead of this error message I would have expected this:
```
Resolved version 1.105.1 to version 1.105.1
Could not determine file extension from URL https://update.code.visualstudio.com/1.105.1/win32-x64-archive/stable - guess was zip but may be incorrect.
Trying to download vscode-1.105.1-windows-x64.zip from https://update.code.visualstudio.com/1.105.1/win32-x64-archive/stable
Step 'ide' ended with failure.
Step 'ide (vscode)' failed: java.lang.IllegalStateException: Download of vscode-1.105.1-windows-x64.zip failed after trying 1 URL(s).
1 step(s) failed out of 2 steps.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/IDEasy/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Download+of+vscode-1.105.1-windows-x64.zip+failed+after+trying+1+URL%28s%29.
java.lang.IllegalStateException: Download of vscode-1.105.1-windows-x64.zip failed after trying 1 URL(s).
	at com.devonfw.tools.ide.tool.repository.AbstractToolRepository.download(AbstractToolRepository.java:130)
	at com.devonfw.tools.ide.tool.repository.AbstractToolRepository.doDownload(AbstractToolRepository.java:98)
	at com.devonfw.tools.ide.tool.repository.AbstractToolRepository.download(AbstractToolRepository.java:82)
	at com.devonfw.tools.ide.tool.repository.AbstractToolRepository.download(AbstractToolRepository.java:65)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.downloadTool(LocalToolCommandlet.java:289)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.performToolInstallation(LocalToolCommandlet.java:264)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:243)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:187)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstallStep(LocalToolCommandlet.java:100)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.install(LocalToolCommandlet.java:90)
	at com.devonfw.tools.ide.tool.ide.IdeToolCommandlet.install(IdeToolCommandlet.java:63)
	at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:194)
	at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:175)
	at com.devonfw.tools.ide.tool.ide.IdeToolCommandlet.runTool(IdeToolCommandlet.java:56)
	at com.devonfw.tools.ide.tool.ToolCommandlet.run(ToolCommandlet.java:151)
	at com.devonfw.tools.ide.tool.ide.IdeToolCommandlet.run(IdeToolCommandlet.java:50)
	at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:1144)
	at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:1054)
	at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:99)
	at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:59)
	at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:137)
Caused by: java.lang.IllegalStateException: Failed to download file from URL https://update.code.visualstudio.com/1.105.1/win32-x64-archive/stable to D:\projects\_ide\tmp\Downloads\vscode-1.105.1-windows-x64.zip
	at com.devonfw.tools.ide.io.FileAccessImpl.downloadViaHttp(FileAccessImpl.java:137)
	at com.devonfw.tools.ide.io.FileAccessImpl.download(FileAccessImpl.java:102)
	at com.devonfw.tools.ide.tool.repository.AbstractToolRepository.download(AbstractToolRepository.java:197)
	at com.devonfw.tools.ide.tool.repository.AbstractToolRepository.download(AbstractToolRepository.java:122)
	... 20 more
Caused by: java.lang.IllegalStateException: Failed to stream response body from url: https://update.code.visualstudio.com/1.105.1/win32-x64-archive/stable
	at com.devonfw.tools.ide.io.HttpDownloader.httpGet(HttpDownloader.java:89)
	at com.devonfw.tools.ide.io.FileAccessImpl.downloadWithHttpVersion(FileAccessImpl.java:148)
	at com.devonfw.tools.ide.io.FileAccessImpl.downloadViaHttp(FileAccessImpl.java:122)
	... 23 more
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:960)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
	at com.devonfw.tools.ide.io.HttpDownloader.httpGet(HttpDownloader.java:81)
	... 25 more
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:130)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:383)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1327)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1204)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1147)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:393)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:476)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1273)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1260)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1205)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.lambda$executeTasks$3(SSLFlowDelegate.java:1148)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:177)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.executeTasks(SSLFlowDelegate.java:1143)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.doHandshake(SSLFlowDelegate.java:1109)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:508)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:283)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:182)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:388)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:271)
	at java.base/sun.security.validator.Validator.validate(Validator.java:256)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:284)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1305)
	... 21 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:383)
	... 26 more
```

### IDEasy status

```bash
Updates are available for the settings repository. If you want to apply the latest changes, call "ide update"
IDE_ROOT is set to D:/projects
IDE_HOME is set to D:/projects/project
You are online.
Your settings are not up-to-date, please run 'ide update'.
Your version of IDEasy is 2025.10.002-SNAPSHOT.
You are using a SNAPSHOT version of IDEasy. For stability consider switching to a stable release via 'ide upgrade --mode=stable'
Your version of IDEasy is 2025.10.002-SNAPSHOT but version 2025.10.002-20251028.024339-2 is available. Please run the following command to upgrade to the latest version:
ide upgrade
Your operating system is windows(10.0)@x64 [Windows 11@amd64]
Successfully completed ide (status)
```

### Related/Dependent issues

_No response_

### Comments/Hints

Can easily be fixed through returning an IllegalStateException instead of a CliException.

### PR DESCRIPTION
**Pull request by jan-vcapgemini**
### Implemented changes:

* changed the download exception from CliException to IllegalStateException

---

## Checklist for this PR

Make sure everything is checked before merging this PR. For further info please also see
our [DoD](https://github.com/devonfw/IDEasy/blob/main/documentation/DoD.adoc).

- [x] When running `mvn clean test` locally all tests pass and build is successful
- [x] PR title is of the form `#«issue-id»: «brief summary»` (e.g. `#921: fixed setup.bat`). If no issue ID exists, title only.
- [x] PR top-level comment summarizes what has been done and contains link to addressed issue(s)
- [x] PR and issue(s) have suitable labels
- [x] Issue is set to `In Progress` and assigned to you *or* there is no issue (might happen for very small PRs)
- [x] You followed all [coding conventions](https://github.com/devonfw/IDEasy/blob/main/documentation/coding-conventions.adoc)
- [x] You have added the issue implemented by your PR in [CHANGELOG.adoc](https://github.com/devonfw/IDEasy/blob/main/CHANGELOG.adoc) unless issue is labeled
  with `internal`

### CODE REVIEW

File: cli/src/main/java/com/devonfw/tools/ide/cli/Ideasy.java [hunk 1]
```diff
@@ -59,9 +59,13 @@ public int run(String... args) {
...
-      String errorMessage = error.getMessage();
-      if ((errorMessage != null) && !errorMessage.isBlank()) {
-        context().error(errorMessage);
+      if (context().debug().isEnabled()) {
+        context().error(error);
+      } else {
+        String errorMessage = error.getMessage();
+        if ((errorMessage != null) && !errorMessage.isBlank()) {
+          context().error(errorMessage);
+        }
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/cli/Ideasy.java]: This is not required for the fix.
I would propose to revert it from here and create a new ticket and PR for the general feature that when debug is enabled we also get stacktraces of CliExceptions.
```suggestion
      String errorMessage = error.getMessage();
      if ((errorMessage != null) && !errorMessage.isBlank()) {
        context().error(errorMessage);
```

**Review by hohwille — APPROVED** [review]
@jan-vcapgemini thanks for the fix. Great that we do not eat up important stack-traces hiding relevant information. 👍
