### PR TITLE
#1384: Add python support via uv

### LINKED ISSUE #1384: Python support not working at all
### Actual behavior

When I setup Python via IDEasy I do not get a usable installation of Python.
Instead I can see an `$IDE_HOME/software/python` folder containing the installer binary (`python-3.11.9-amd64.exe`).
The release of Python e.g. https://github.com/actions/python-versions/releases/download/3.11.9-8525206794/python-3.11.9-win32-x64.zip is kind of nuts since the ZIP only contains an installer instead of a portable software release.
This results in a useless/broken installation.

### Reproduce

1. ide create python-test-project -
2. icd -p python-test-project
3. ide install python
4. python --version
5. ls software/python

### Expected behavior

Python gets installed properly so that step 4. (see Reproduce) is successful.

### IDEasy status

```bash
Updates are available for the settings repository. If you want to apply the latest changes, call "ide update"
IDE_ROOT is set to D:\projects
IDE_HOME is set to D:\projects\test
You are online.
Your settings are not up-to-date, please run 'ide update'.
Your version of IDEasy is 2025.06.002-06_07_02-SNAPSHOT but version 2025.06.002-20250619.024441-3 is available. Please run the following command to upgrade to the latest version:
ide upgrade
Your operating system is windows(10.0)@x64 [Windows 11@amd64]
```

### Related/Dependent issues

#1325, #1046

### Comments/Hints

It seems that #38 was implemented with PR #1073 but this was never ever tested at all.
Therefore Python support in IDEasy was never functional.

BTW: We have implemented support in IDEasy to unpack various archives like ZIP, MSI, TAR.GZ, DMG, etc.
However, Python is giving us a hard time since it provides a ZIP containing an EXE file.
We already unpack the ZIP but would also need to unpack the EXE file within the ZIP.
We neither have support of chaining unpacking of nested formats nor do we have support to "unpack" an EXE that is actually an installer and IMHO there is not even a generic possible way to do this.
Further this is also only the situation on Windows. On MacOS and on Linux there are other problems.
Python again gives us such a hard time since many years (already was pure pain in devonfw-ide).
See also https://github.com/devonfw/IDEasy/blob/main/documentation/tool-vendor-plea.adoc
Why can't Python just provide a portable binary release as ZIP or TAR.GZ for all major platforms just as every other reasonable software project does?
See also https://discuss.python.org/t/automation-of-portable-installation-for-python-and-python-based-tools/20256

For the problem on Windows try and check the `setup.ps1` script that may contain the logic how to "unpack" the EXE and create the proper installation.

### PR DESCRIPTION
**Pull request by juliane-cap**
### Implemented changes:

* Add python installation logic via uv
* Add a uv commandlet
* Adjust installation logic so it can be overridden for special python handeling without too much redundancy
* Fix infrastructure of some test projects by adding or moving urls-files

---

## Checklist for this PR

Make sure everything is checked before merging this PR. For further info please also see
our [DoD](https://github.com/devonfw/IDEasy/blob/main/documentation/DoD.adoc).

- [x] When running `mvn clean test` locally all tests pass and build is successful
- [x] PR title is of the form `#«issue-id»: «brief summary»` (e.g. `#921: fixed setup.bat`). If no issue ID exists, title only.
- [x] PR top-level comment summarizes what has been done and contains link to addressed issue(s)
- [x] PR and issue(s) have suitable labels
- [x] Issue is set to `In Progress` and assigned to you *or* there is no issue (might happen for very small PRs)
- [x] You followed all [coding conventions](https://github.com/devonfw/IDEasy/blob/main/documentation/coding-conventions.adoc)
- [x] You have added the issue implemented by your PR in [CHANGELOG.adoc](https://github.com/devonfw/IDEasy/blob/main/CHANGELOG.adoc) unless issue is labeled
  with `internal`

### Checklist for tool commandlets

Have you added a new `«tool»` as commandlet? There are the following additional checks:

- [x] The tool can be installed automatically (during setup via settings) or via the commandlet call
- [x] The tool is isolated in its IDEasy project, see [Sandbox Principle](https://github.com/devonfw/IDEasy/blob/main/documentation/sandbox.adoc)
- [x] The new tool is added to the table of tools in [LICENSE.asciidoc](https://github.com/devonfw/IDEasy/blob/main/documentation/LICENSE.adoc)
- [x] The new commandlet is a [command-wrapper](https://github.com/devonfw/IDEasy/blob/main/documentation/cli.adoc#command-wrapper) for `«tool»`
- [x] Proper help texts for all supported languages are added [here](https://github.com/devonfw/IDEasy/tree/main/cli/src/main/resources/nls)
- [x] The new commandlet installs potential dependencies automatically
- [x] The variables `«TOOL»_VERSION` and `«TOOL»_EDITION` are honored by your commandlet
- [ ] The new commandlet is tested on all platforms it is available for or tested on all platforms that are in scope of the linked issue

### CODE REVIEW

File: cli/src/main/java/com/devonfw/tools/ide/common/SystemPath.java [hunk 1]
```diff
@@ -128,6 +128,12 @@ private void collectToolPath(Path softwarePath) {
           String tool = child.getFileName().toString();
           if (!"extra".equals(tool) && Files.isDirectory(child)) {
             Path toolPath = child;
+            if (tool.equals("python")) {
+              Path venvScripts = child.resolve(".venv").resolve("Scripts");
+              if (Files.isDirectory(venvScripts)) {
+                toolPath = venvScripts;
+              }
+            }
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/common/SystemPath.java:136]: This is python specific code in a generic class for system path handling.
1. IMHO the `Scripts` folder only exists on Windows and on other platforms `bin` is used. This is Python legacy heritage. Stupid but will never change.
2. You could move this code to python (at least what is inside the if) commandlet, but what about this: The `uv` commandlet will install to `software/uv/` and creates a `.venv` folder there. The Python commandlet will install pyhton in `.venv` but create a symlink `pyhton` pointing to `uv/.venv` inside the software folder and on Windows we create a symlink `bin` pointing to `Scripts` inside the `software/uv/.venv` folder.
3. Did you ever try if the `.venv` folder name is required or we can use any folder? Can we also use `software/python` instead of `software/uv/.venv` to prevent creating the symlink at all?

Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/common/SystemPath.java:136]: If 2. (and maybe 3.)  works out, we can remove this code here entirely and simplify our code avoiding quirks.

Comment (juliane-cap) [reply cli/src/main/java/com/devonfw/tools/ide/common/SystemPath.java:136]: The path that needs to be added to PATH  for Windows is `software/python/.venv/Scripts` and for Linux and MacOS the needed path is `software/python/.venv/bin`

It's two folders deep into the python software repository.

File: cli/src/main/resources/nls/Help.properties [hunk 2]
```diff
@@ -117,6 +117,8 @@ cmd.upgrade-settings=Commandlet to upgrade settings of a devonfw-ide project, to
 cmd.upgrade-settings.detail=Renames and reconfigures all devon.properties, replaces all legacy variables, updates folder names and points out all xml files that are not compatible for the xml merger.
 cmd.upgrade.detail=Automatically checks for and installs the latest available version. If using a Snapshot version of IDEasy, this command will install the latest available Snapshot.
 cmd.upgrade.opt.--mode=the upgrade mode (e.g. '--mode=stable` for the latest stable release).
+cmd.uv=Tool commandlet for uv (python package manager).
+cmd.uv.detail=uv is a Python package and project manager. Used by IDEasy internally to install Python and manage pip dependencies. Detailed documentation can be found at https://docs.astral.sh/uv/
```
Comment (jan-vcapgemini) [inline cli/src/main/resources/nls/Help.properties:121]:
```suggestion
cmd.uv.detail=uv is a Python package and project manager. Used by IDEasy internally to install Python and manage pip dependencies. Detailed documentation can be found at: https://docs.astral.sh/uv/
```

File: cli/src/main/java/com/devonfw/tools/ide/tool/uv/Uv.java [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+   * The constructor.
+   *
+   * @param context the {@link IdeContext}.
+   */
+  public Uv(IdeContext context) {
+
+    super(context, "uv", Set.of(Tag.PYTHON));
+  }
+
+  public void installPython(Path installationPath, VersionIdentifier resolvedVersion, ProcessContext processContext) {
```
[the remark this answers is not in the document]
Comment (juliane-cap) [reply cli/src/main/java/com/devonfw/tools/ide/tool/uv/Uv.java]: Added in next commit

File: cli/src/main/java/com/devonfw/tools/ide/tool/uv/Uv.java [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+import com.devonfw.tools.ide.common.Tag;
+import com.devonfw.tools.ide.context.IdeContext;
+import com.devonfw.tools.ide.process.ProcessContext;
+import com.devonfw.tools.ide.process.ProcessErrorHandling;
+import com.devonfw.tools.ide.process.ProcessMode;
+import com.devonfw.tools.ide.process.ProcessResult;
+import com.devonfw.tools.ide.tool.LocalToolCommandlet;
+import com.devonfw.tools.ide.version.VersionIdentifier;
+
+public class Uv extends LocalToolCommandlet {
```
[the remark this answers is not in the document]
Comment (juliane-cap) [reply cli/src/main/java/com/devonfw/tools/ide/tool/uv/Uv.java]: Added in next commit

**Review by jan-vcapgemini — APPROVED** [review]
Thanks for applying my CRs, ready for review now.

**Comment by hohwille** [comment]
I plan some final testing on Monday, when `uv` is populated in ide-urls and https://github.com/devonfw/ide-urls/pull/29 is merged. Then we will also merge this and include it in the release.

**Comment by hohwille** [comment]
Successfully tested on Ubuntu linux:
```
$ python
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
$ ide install python
Trying to download uv-0.8.12-linux-x64.tar.gz from https://github.com/astral-sh/uv/releases/download/0.8.12/uv-x86_64-unknown-linux-gnu.tar.gz
Downloading 100% │█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████│ 18/18MiB (0:00:00 / 0:00:00) ?MiB/s
SHA-256 checksum f976ebdc612e71209f46664ab6c0325fa0090059b4474e047edd39eb9395373b is correct.
Extracting TAR file ~/Downloads/ide/default/uv-0.8.12-linux-x64.tar.gz to ~/projects/_ide/tmp/extract-uv-0.8.12-linux-x64.tar.gz
Extracting 100% │██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████│ 18/18MiB (0:00:00 / 0:00:00) ?MiB/s
Successfully installed uv in version 0.8.12
Successfully installed python in version 3.11.13
$ which python
~/projects/IDEasy/software/python/bin/python
$ python --version
Python 3.11.13
$ ide install python 3.10.11
PYTHON_VERSION=3.10.11 has been set in SETTINGS@~/projects/IDEasy/settings/ide.properties
Version 0.8.12 of tool uv is already installed
Successfully installed python in version 3.10.11
$ python --version
Python 3.10.11
```

The only problem I could find is that not all versions we detect via Url-Updater and therefore suggest via auto-completion are supported by `uv`:
```
$ ide install python 3.10.1
PYTHON_VERSION=3.10.1 has been set in SETTINGS@~/projects/IDEasy/settings/ide.properties
Version 0.8.12 of tool uv is already installed
Creating backup by moving ~/projects/IDEasy/software/python to ~/projects/IDEasy/backups/2025/08/19/08-27-20_python/IDEasy/software/python
Running command '~/projects/IDEasy/software/uv/uv' with arguments 'venv' '--python' '3.10.1'
failed with exit code 2!
error: No interpreter found for Python 3.10.1 in managed installations or search path
Running command '~/projects/IDEasy/software/uv/uv' with arguments 'venv' '--python' '3.10.1'
failed with exit code 2!
```

We can file a new bug ticket for that but I do not see a big problem in this. I guess we could simply set such versions to `manual` in `status.json` and remove the `*urls*` files from it.

**Comment by hohwille** [comment]
Also tested on Mac OS x64 and Windows x64. All working fine. `uv` rocks!
