### PR TITLE
#1551: add NetworkStatus and improve status commandlet

### LINKED ISSUE #1551: Display network connection issues in status
### Feature idea

As an IDEasy user I need to be able to analyse problems with my network setup before I start to use IDEasy productively so that I won't run into repeating issues when I try to install tools etc.

Instead of writing `You are offline` we should distinguish further into variants like:
* `You are having TLS issues. We guess you are forced to use a VPN tool breaking end-to-end encryption causing this effect. As a workaround you can call the following command: ide fix-vpn-tls-problem`
* `You seem to be offline since our online check failed with: java.net.UnknownHostException: www.github.com`
* ...

### Technical Details

Currently we have methods like `isOnline()` and `isOffline()`. With this story we want to create a new method `getOnlineStatus()` returning an `OnlineStatus` object with methods `isOnline()` and `isOffline()` but also `getError()` returning the causing `IOException` (or `null` if we are online) and `isTlsError()` to easily determine if the TLS issue was detected from the error exception.

### Additional context

This is a sub-issue of #897

### PR DESCRIPTION
**Pull request by hohwille**
### Implemented changes:

* added `NetworkStatus` interface and its implementation
* reworked `IdeContext`
* updated `StatusCommandlet` to use `NetworkStatus`
* adapted and improved tests

---

## Checklist for this PR

Make sure everything is checked before merging this PR. For further info please also see
our [DoD](https://github.com/devonfw/IDEasy/blob/main/documentation/DoD.adoc).

- [x] When running `mvn clean test` locally all tests pass and build is successful
- [x] PR title is of the form `#«issue-id»: «brief summary»` (e.g. `#921: fixed setup.bat`). If no issue ID exists, title only.
- [x] PR top-level comment summarizes what has been done and contains link to addressed issue(s)
- [x] PR and issue(s) have suitable labels
- [x] Issue is set to `In Progress` and assigned to you *or* there is no issue (might happen for very small PRs)
- [x] You followed all [coding conventions](https://github.com/devonfw/IDEasy/blob/main/documentation/coding-conventions.adoc)
- [x] You have added the issue implemented by your PR in [CHANGELOG.adoc](https://github.com/devonfw/IDEasy/blob/main/CHANGELOG.adoc) unless issue is labeled
  with `internal`

### CODE REVIEW

File: cli/src/test/java/com/devonfw/tools/ide/commandlet/StatusCommandletTest.java [hunk 1]
```diff
@@ -33,6 +36,26 @@ public void testStatusOutsideOfHome() {
     assertThat(context).logAtWarning().hasMessageContaining("You are not inside an IDE project: ");
   }
 
+  /**
+   * Tests the output if {@link StatusCommandlet} is run without internet connection.
```
Comment (jan-vcapgemini) [inline cli/src/test/java/com/devonfw/tools/ide/commandlet/StatusCommandletTest.java]:
```suggestion
   * Tests the output if {@link StatusCommandlet} is run in enforced offline mode.
```

File: cli/src/main/java/com/devonfw/tools/ide/network/NetworkStatusImpl.java [hunk 2]
```diff
@@ -0,0 +1,135 @@
...
+    if (this.context.debug().isEnabled()) {
+      this.context.error(error, message);
+    } else {
+      this.context.error(message);
+      this.context.error(error.toString());
+    }
+    if (error instanceof SSLException) {
+      this.context.warning(
+          "You are having TLS issues. We guess you are forced to use a VPN tool breaking end-to-end encryption causing this effect. As a workaround you can call the following command:");
+      this.context.interaction("ide fix-vpn-tls-problem");
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/network/NetworkStatusImpl.java]: Untill we have implemented the suggestion in #897 and have the `fix-vpn-tls-problem` commandlet, we should log something else here:

```suggestion
          "You are having TLS issues. We guess you are forced to use a VPN tool breaking end-to-end encryption causing this effect. As a workaround you can create and configure a truststore as described here:");
      this.context.interaction("https://github.com/devonfw/IDEasy/blob/main/documentation/proxy-support.adoc#tls-certificate-issues");
```

File: cli/src/main/java/com/devonfw/tools/ide/network/NetworkStatusImpl.java [hunk 3]
```diff
@@ -0,0 +1,136 @@
...
+    String message = "You are offline because of the following error:";
+    if (this.context.debug().isEnabled()) {
+      this.context.error(error, message);
+    } else {
+      this.context.error(message);
+      this.context.error(error.toString());
+    }
+    if (error instanceof SSLException) {
+      this.context.warning(
+          "You are having TLS issues. We guess you are forced to use a VPN tool breaking end-to-end encryption causing this effect. As a workaround you can call the following command:");
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/network/NetworkStatusImpl.java]: GitHub suggestion feature buggy?
```suggestion
```
