### PR TITLE
#1387: throw CliException when tool version not supported for OS

### LINKED ISSUE #1387: Hide exception from user when a tool version is not supported
### Task summary

The exception from #1368 is not helpful to the user, we need to disable it when IDEasy is not in debug mode.

```
java.lang.IllegalStateException: No download was found for OS mac@arm64 in /Users/<username>/projects/_ide/urls/java/java/17.0.15_6
    at com.devonfw.tools.ide.url.model.folder.UrlVersion.getMatchingUrls(UrlVersion.java:112)
    at com.devonfw.tools.ide.tool.repository.DefaultToolRepository.getMetadata(DefaultToolRepository.java:46)
    at com.devonfw.tools.ide.tool.repository.AbstractToolRepository.download(AbstractToolRepository.java:58)
    at com.devonfw.tools.ide.tool.LocalToolCommandlet.downloadTool(LocalToolCommandlet.java:238)
    at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:216)
    at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:169)
    at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstallStep(LocalToolCommandlet.java:89)
    at com.devonfw.tools.ide.tool.LocalToolCommandlet.install(LocalToolCommandlet.java:79)
    at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:262)
    at com.devonfw.tools.ide.commandlet.InstallCommandlet.run(InstallCommandlet.java:77)
    at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:1021)
    at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:931)
    at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:95)
    at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:59)
    at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:133)
    at java.base@23.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)

Error: IDEasy failed with exit code 255
```

### Additional context

JH: IMHO the exception is helpful but we could throw a `CliException` to suppress the stacktrace.
I do not know what "hiding" means but without further details I fear that the next developer implementing this story will just remove the throws clause and try to continue the code flow ignoring the error only leading to bigger problems.
Be careful when creating new stories to explain what you imply and try to give instructions what should actually be done.

### PR DESCRIPTION
**Pull request by juliane-cap**
### Implemented changes:

* throw CliException instead of IllegalStateException when tool version is not supported on current OS

Can betested on Windows by running:
`ide install vscode 1.12.0`
Can be tested on Linux by running:
`ide install az 2.52.0`

---

## Checklist for this PR

Make sure everything is checked before merging this PR. For further info please also see
our [DoD](https://github.com/devonfw/IDEasy/blob/main/documentation/DoD.adoc).

- [x] When running `mvn clean test` locally all tests pass and build is successful
- [x] PR title is of the form `#«issue-id»: «brief summary»` (e.g. `#921: fixed setup.bat`). If no issue ID exists, title only.
- [x] PR top-level comment summarizes what has been done and contains link to addressed issue(s)
- [x] PR and issue(s) have suitable labels
- [x] Issue is set to `In Progress` and assigned to you *or* there is no issue (might happen for very small PRs)
- [x] You followed all [coding conventions](https://github.com/devonfw/IDEasy/blob/main/documentation/coding-conventions.adoc)
- [x] You have added the issue implemented by your PR in [CHANGELOG.adoc](https://github.com/devonfw/IDEasy/blob/main/CHANGELOG.adoc) unless issue is labeled
  with `internal`

### CODE REVIEW

File: cli/src/main/java/com/devonfw/tools/ide/url/model/UrlMetadata.java [hunk 1]
```diff
@@ -87,7 +87,7 @@ private List<VersionIdentifier> computeSortedVersions(String tool, String editio
       try {
         urlVersion.getMatchingUrls(sys.getOs(), sys.getArchitecture());
         list.add(versionIdentifier);
-      } catch (IllegalStateException e) {
+      } catch (CliException e) {
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/url/model/UrlMetadata.java:90]: we have completed the last release and opened 2025.08.001 as SNAPSHOT version. Could you now add the story to the changelog?
p.s.: I know this review comment is misplaced but GitHub does not over another way to add a review CR not related to a code-line that was changed and when I write it only in the review comment summary it often gets forgotten.
But since I am annotation this line: I already checked that this is the only single exception situation so the change is safe.
However, just as a thought we could also sub-class and throw + catch a more specific variant of `CliException` for this scenario.

**Review by hohwille — APPROVED** [review]
@juliane-cap thanks for your PR and fixing this. LGTM 👍

**Review by jan-vcapgemini — APPROVED** [review]
LGTM. Ready for review.
