### PR TITLE
#1602: Being offline can block ide startup

### LINKED ISSUE #1602: Being offline can block ide startup
### Actual behavior

I want to start intellij while there is an already available update of the ide listed but not yet installed in the cloned urls repository. This leads to an exception blocking me from starting my idea if it cannot be updated with the following message:

```
$ ide intellij
Updates are available for the settings repository. If you want to apply the latest changes, call "ide update"
Start: Configuring workspace core for IDE intellij
Successfully ended step 'Configuring workspace core for IDE intellij'.
Skipping git pull/clone on D:\projects\_ide\urls because we are offline.
Step 'ide (intellij)' failed: com.devonfw.tools.ide.cli.CliOfflineException: Not able to download tool intellij in edition ultimate with version 2025.2.4 because we are offline
1 step(s) failed out of 2 steps.
Not able to download tool intellij in edition ultimate with version 2025.2.4 because we are offline

Error: IDEasy failed with exit code 23
```

### Reproduce

1. enforcing an older ide version of intellij, not the recent by settings
2. once run ide update to get latest urls
3. connect to a different vpn, remove proxy, or disconnect from internet to enter offline mode (in my case not having proper proxy setup as of vpn switch)
4. remove the version restriction for intellij in the settings leading to a potential update to a newer version from now on
5. run `ide intellij` which will automatically trigger the update

### Expected behavior

Although the most recent version cannot be downloaded, the current version still should work!

### IDEasy status

```bash
$ ide -p status
Updates are available for the settings repository. If you want to apply the latest changes, call "ide update"
IDE_ROOT is set to D:/projects
IDE_HOME is set to D:/projects/project
You are offline. Check your internet connection and potential proxy settings.
Your settings are not up-to-date, please run 'ide update'.
Your version of IDEasy is 2025.10.002.
Skipping check for newer version of IDEasy because you are offline.
Your operating system is windows(10.0)@x64 [Windows 11@amd64]
Successfully completed ide (status)
```

### Related/Dependent issues

_No response_

### Comments/Hints

_No response_

### PR DESCRIPTION
**Pull request by maybeec**
## Description
Fixes issue #1602: Being offline can block IDE startup when a tool update is available but not cached.

### Core Fix
- **AbstractToolRepository.java**: Enhanced `doDownload()` to check if download is already cached before throwing `CliOfflineException` in offline mode
- **LocalToolCommandlet.java**: 
  - Modified `performToolInstallation()` to return `VersionIdentifier` indicating which version was actually installed
  - Added proper offline fallback logic that returns existing installed version when download fails
  - Fixed installation path calculation to use actual installed version instead of requested version

### Supporting Changes
- **Python.java**: Updated override to match new `performToolInstallation()` signature
- **PackageManagerBasedLocalToolCommandlet.java**: Updated override to match new signature

### Tests
Added comprehensive test coverage in **InstallCommandletTest.java**:
- `testInstallCommandletOfflineWithCachedDownload`: Fresh install with cached download succeeds
- `testInstallCommandletOfflineWithoutCachedDownload`: Fresh install without cache fails appropriately
- `testInstallCommandletOfflineUpdateWithoutCachedDownload`: Update scenario keeps old version when new version not cached

### Documentation
- Updated **CHANGELOG.adoc** with issue #1602 entry

## Testing
All offline scenario tests pass successfully:
```
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
```

## Checklist
- [x] Code compiles successfully
- [x] New tests added and passing
- [x] Coding conventions followed (AssertJ for assertions, proper error handling)
- [x] CHANGELOG.adoc updated
- [x] Design reviewed and refactored to avoid duplication
- [x] Commit message follows format: `#1602: Being offline can block ide startup`

## Related Issue
Closes #1602

### CODE REVIEW

**Review by hohwille — APPROVED** [review]
@maybeec thanks for your PR. This is a really great improvement that I like to merge.
I was not really aware of this problem that we check for offline and throw an exception before we check that the download may already been cached....
FYI: I always told the development team that I consider it as an anti-pattern to do an explicit online check and throw an offline exception prior to invoking network activity.
I created `invokeNetworkTask` as a reasonable alternative to get what we really want.
Example:
https://github.com/devonfw/IDEasy/blob/0c7f3d0ecd706e6e1f2bf3295c50252522067208/cli/src/main/java/com/devonfw/tools/ide/tool/mvn/MvnRepository.java#L282-L287

This way we simply perform the network operation and if we get a network issue (e.g. IOException) then this is stored as the latest network error and considered for our offline/online status. Our artificial online check is just pinging github.com and it may be unlikely that this fails. However, I have already seen situation where that failed due to ZScaler interfering while some other tool download worked fine.

File: cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java [hunk 1]
```diff
@@ -199,8 +200,13 @@ public ToolInstallation installTool(ToolInstallRequest request) {
...
     }
-    performToolInstallation(request, installationPath);
-    return createToolInstallation(installationPath, resolvedVersion, true, processContext, additionalInstallation);
+    VersionIdentifier actualInstalledVersion = performToolInstallation(request, installationPath, resolvedVersion);
+    // If offline and could not download, actualInstalledVersion will be the old version, not resolvedVersion
+    // In that case, we need to recalculate the installation path for the actually installed version
+    if (!actualInstalledVersion.equals(resolvedVersion)) {
+      installationPath = getInstallationPath(edition, actualInstalledVersion);
+    }
+    return createToolInstallation(installationPath, actualInstalledVersion, true, processContext, additionalInstallation);
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java]:
```suggestion
    try {
      performToolInstallation(request, installationPath);
    } catch (CliOfflineException e) {
      // If we are offline and cannot download, check if we can continue with an existing installation
      ToolEditionAndVersion installed = request.getInstalled();
      if ((installed != null) && (installed.getResolvedVersion() != null)) {
        this.context.warning("Cannot download {} in version {} because we are offline. Continuing with already installed version {}.", this.tool, resolvedVersion, installed.getResolvedVersion());
        // If offline and could not download, actualInstalledVersion will be the old version, not resolvedVersion
        // In that case, we need to recalculate the installation path for the actually installed version
        installationPath = getInstallationPath(edition, installed.getResolvedVersion());
      }
      // No existing installation available, re-throw the exception
      throw e;
    }
    return createToolInstallation(installationPath, actualInstalledVersion, true, processContext, additionalInstallation);
```

File: cli/src/main/java/com/devonfw/tools/ide/tool/python/Python.java [hunk 2]
```diff
@@ -35,9 +35,8 @@ public Python(IdeContext context) {
   }
 
   @Override
-  protected void performToolInstallation(ToolInstallRequest request, Path installationPath) {
+  protected VersionIdentifier performToolInstallation(ToolInstallRequest request, Path installationPath, VersionIdentifier resolvedVersion) {
 
-    VersionIdentifier resolvedVersion = request.getRequested().getResolvedVersion();
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/tool/python/Python.java]:
```suggestion
  protected void performToolInstallation(ToolInstallRequest request, Path installationPath) {
    VersionIdentifier resolvedVersion = request.getRequested().getResolvedVersion();
```

File: cli/src/main/java/com/devonfw/tools/ide/tool/PackageManagerBasedLocalToolCommandlet.java [hunk 3]
```diff
@@ -177,12 +177,13 @@ public VersionIdentifier getInstalledVersion() {
...
-  protected final void performToolInstallation(ToolInstallRequest request, Path installationPath) {
+  protected final VersionIdentifier performToolInstallation(ToolInstallRequest request, Path installationPath, VersionIdentifier resolvedVersion) {
 
     PackageManagerRequest packageManagerRequest = new PackageManagerRequest(PackageManagerRequest.TYPE_INSTALL, getPackageName())
-        .setProcessContext(request.getProcessContext()).setVersion(request.getRequested().getResolvedVersion());
+        .setProcessContext(request.getProcessContext()).setVersion(resolvedVersion);
     runPackageManager(packageManagerRequest, true).failOnError();
     this.installedVersion.invalidate();
+    return resolvedVersion;
   }
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/tool/PackageManagerBasedLocalToolCommandlet.java]:
```suggestion
  protected final void performToolInstallation(ToolInstallRequest request, Path installationPath) {

    PackageManagerRequest packageManagerRequest = new PackageManagerRequest(PackageManagerRequest.TYPE_INSTALL, getPackageName())
        .setProcessContext(request.getProcessContext()).setVersion(request.getRequested().getResolvedVersion());
    runPackageManager(packageManagerRequest, true).failOnError();
    this.installedVersion.invalidate();
  }
```

**Comment by hohwille** [comment]
OK, GitHub still has some flaws for constructive reviews:
> Unable to apply suggestions on deleted lines.

Seems I have to temporary create broken states and failed builds...

File: cli/src/main/java/com/devonfw/tools/ide/tool/python/Python.java [hunk 4]
```diff
@@ -35,9 +35,8 @@ public Python(IdeContext context) {
   }
 
   @Override
-  protected void performToolInstallation(ToolInstallRequest request, Path installationPath) {
+  protected VersionIdentifier performToolInstallation(ToolInstallRequest request, Path installationPath, VersionIdentifier resolvedVersion) {
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/tool/python/Python.java]:
```suggestion
  protected void performToolInstallation(ToolInstallRequest request, Path installationPath) {
```

File: cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java [hunk 5]
```diff
@@ -212,13 +218,29 @@ public ToolInstallation installTool(ToolInstallRequest request) {
...
+      ToolEditionAndVersion installed = request.getInstalled();
+      if ((installed != null) && (installed.getResolvedVersion() != null)) {
+        this.context.warning("Cannot download {} in version {} because we are offline. Continuing with already installed version {}.",
+            this.tool, resolvedVersion, installed.getResolvedVersion());
+        // Return the existing installed version to indicate fallback
+        return installed.getResolvedVersion();
+      }
+      // No existing installation available, re-throw the exception
+      throw e;
+    }
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java]:
```suggestion
    VersionIdentifier resolvedVersion = requested.getResolvedVersion();
    Path downloadedToolFile = downloadTool(requested.getEdition().edition(), resolvedVersion);
```

File: cli/src/main/java/com/devonfw/tools/ide/tool/PackageManagerBasedLocalToolCommandlet.java [hunk 6]
```diff
@@ -177,12 +177,13 @@ public VersionIdentifier getInstalledVersion() {
...
 
   @Override
-  protected final void performToolInstallation(ToolInstallRequest request, Path installationPath) {
+  protected final VersionIdentifier performToolInstallation(ToolInstallRequest request, Path installationPath, VersionIdentifier resolvedVersion) {
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/tool/PackageManagerBasedLocalToolCommandlet.java]:
```suggestion
  protected final void performToolInstallation(ToolInstallRequest request, Path installationPath) {
```

File: cli/src/main/java/com/devonfw/tools/ide/tool/PackageManagerBasedLocalToolCommandlet.java [hunk 7]
```diff
@@ -177,12 +177,13 @@ public VersionIdentifier getInstalledVersion() {
...
 
     PackageManagerRequest packageManagerRequest = new PackageManagerRequest(PackageManagerRequest.TYPE_INSTALL, getPackageName())
-        .setProcessContext(request.getProcessContext()).setVersion(request.getRequested().getResolvedVersion());
+        .setProcessContext(request.getProcessContext()).setVersion(resolvedVersion);
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/tool/PackageManagerBasedLocalToolCommandlet.java]:
```suggestion
        .setProcessContext(request.getProcessContext()).setVersion(request.getRequested().getResolvedVersion());
```

File: cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java [hunk 8]
```diff
@@ -234,6 +256,7 @@ protected void performToolInstallation(ToolInstallRequest request, Path installa
     fileAccess.extract(downloadedToolFile, installationPath, this::postExtract, extract);
     this.context.writeVersionFile(resolvedVersion, installationPath);
     this.context.debug("Installed {} in version {} at {}", this.tool, resolvedVersion, installationPath);
+    return resolvedVersion;
```
[the remark this answers is not in the document]
Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java]: GitHub is broken. Suggestion could not be applied. Did it manually via editing file.

File: cli/src/main/java/com/devonfw/tools/ide/tool/PackageManagerBasedLocalToolCommandlet.java [hunk 9]
```diff
@@ -177,12 +177,13 @@ public VersionIdentifier getInstalledVersion() {
...
     runPackageManager(packageManagerRequest, true).failOnError();
     this.installedVersion.invalidate();
+    return resolvedVersion;
```
[the remark this answers is not in the document]
Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/tool/PackageManagerBasedLocalToolCommandlet.java]: GitHub is broken. Suggestion could not be applied. Did it manually via editing file.

File: cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java [hunk 10]
```diff
@@ -199,8 +200,22 @@ public ToolInstallation installTool(ToolInstallRequest request) {
...
+        this.context.warning("Cannot download {} in version {} because we are offline. Continuing with already installed version {}.", this.tool, resolvedVersion, installed.getResolvedVersion());
+        // If offline and could not download, actualInstalledVersion will be the old version, not resolvedVersion
+        // In that case, we need to recalculate the installation path for the actually installed version
+        installationPath = getInstallationPath(edition, installed.getResolvedVersion());
+      } else {
+        // No existing installation available, re-throw the exception
+        throw e;
+      }
+    }
+    return createToolInstallation(installationPath, actualInstalledVersion, true, processContext, additionalInstallation);
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java]: We also need to toggle `true` flag here since this indicates whether we have a new installation or not.
In the case that we changed the `installationPath` and use the existing installation, we need to provide `false`.

Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java]: OK, I was wrong here:
* There is the installation in the software repository that may be new here.
* But the flag is used if the tool itself in the current IDEasy project is newly installed. This is always the case here as otherwise we have already returned earlier.

File: cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java [hunk 11]
```diff
@@ -212,6 +229,9 @@ public ToolInstallation installTool(ToolInstallRequest request) {
    *
    * @param request the {@link ToolInstallRequest}.
    * @param installationPath the target {@link Path} where the {@link #getName() tool} should be installed.
+   * @param resolvedVersion the {@link VersionIdentifier} that should be installed.
+   * @return the {@link VersionIdentifier} of the version that was actually installed. In offline scenarios where download fails, this may be different from
+   *     {@code resolvedVersion} (returning the existing installed version instead).
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java]:
```suggestion
```

File: cli/src/main/java/com/devonfw/tools/ide/tool/repository/AbstractToolRepository.java [hunk 12]
```diff
@@ -92,9 +88,19 @@ protected Path doDownload(UrlDownloadFileMetadata metadata) {
...
+    
     if (Files.exists(target)) {
-      this.context.interaction("Artifact already exists at {}\nTo force update please delete the file and run again.", target);
+      // File is already cached
+      if (this.context.getNetworkStatus().isOffline()) {
+        this.context.debug("Using cached download of {} in version {} from {} (offline mode)", 
+            metadata.getTool(), metadata.getVersion(), target);
+      } else {
+        this.context.interaction("Artifact already exists at {}\nTo force update please delete the file and run again.", target);
+      }
```
[the remark this answers is not in the document]
Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/tool/repository/AbstractToolRepository.java]: Lets resolve and merge.

File: cli/src/main/java/com/devonfw/tools/ide/tool/repository/AbstractToolRepository.java [hunk 13]
```diff
@@ -92,9 +88,19 @@ protected Path doDownload(UrlDownloadFileMetadata metadata) {
...
     } else {
+      if (this.context.getNetworkStatus().isOffline()) {
+        throw CliOfflineException.ofDownloadOfTool(metadata.getTool(), metadata.getEdition(), metadata.getVersion());
+      }
```
[the remark this answers is not in the document]
Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/tool/repository/AbstractToolRepository.java]: Lets resolve and merge.
