### PR TITLE
#1693: Soft-delete corrupted repo after confirmation on 'ide update'

### LINKED ISSUE #1693: Fix behavior when there's no settings repo (.../settings/.git)
### Feature idea

There's strange behavior if the user accidentally deleted the .git settings repository and runs **ide update** to fix this. Packages are installed, but the .git folder is not created.

**Steps to reproduce:**
1. `ide create test -`
2. `icd -p test`
3. `rm -rf settings/.git`
4. `ide update`

**Actual results**:
```
$ ide update
Settings repository exists but is not a git repository.
Start: update (pull) settings repository
Skipping git pull in settings due to code repository. Use --force-pull to enforce pulling.
Successfully ended step 'update (pull) settings repository'.
Start: Copy configuration templates
Successfully ended step 'Copy configuration templates'.
Start: Install or update software
Start: Install node
No CVEs found for version v24.13.0 of tool node.
Version v24.13.0 of tool node is already installed
Successfully ended step 'Install node'.
Start: Install npm
No CVEs found for version 11.8.0 of tool npm.
No CVEs found for version v24.13.0 of tool node.
Version v24.13.0 of tool node is already installed
Version 11.8.0 of tool npm is already installed
Successfully ended step 'Install npm'.
Start: Install mvn
No CVEs found for version 3.9.9 of tool mvn.
No CVEs found for version 25.0.1_8 of tool java.
Version 25.0.1_8 of tool java is already installed
Version 3.9.9 of tool mvn is already installed
Successfully ended step 'Install mvn'.
Start: Install java
No CVEs found for version 25.0.1_8 of tool java.
Version 25.0.1_8 of tool java is already installed
Successfully ended step 'Install java'.
Successfully ended step 'Install or update software'.
Start: Setup of repository IDEasy
The properties file D:\projects\test\settings\repositories\IDEasy.properties uses the legacy property eclipse instead of import
Property eclipse is deprecated and should be replaced with import (invert key and value).
Skipping repository IDEasy because it is not active - use --force to setup all repositories ...
Successfully ended step 'Setup of repository IDEasy'.
Creating start scripts for intellij
Successfully completed ide (update)
```
But no .git folder is created:
```
$ ls -ltra settings/
total 37
drwxr-xr-x 1 ... 4096     0 Jan 27 11:41 ../
-rw-r--r-- 1 ... 4096    71 Jan 27 11:41 .gitignore
-rw-r--r-- 1 ... 4096 11357 Jan 27 11:41 LICENSE
-rw-r--r-- 1 ... 4096   766 Jan 27 11:41 README.asciidoc
drwxr-xr-x 1 ... 4096     0 Jan 27 11:41 android-studio/
drwxr-xr-x 1 ... 4096     0 Jan 27 11:41 checkstyle/
drwxr-xr-x 1 ... 4096     0 Jan 27 11:41 eclipse/
drwxr-xr-x 1 ... 4096     0 Jan 27 11:41 findbugs/
-rw-r--r-- 1 ... 4096  1822 Jan 27 11:41 ide.properties
drwxr-xr-x 1 ... 4096     0 Jan 27 11:41 graalvm/
drwxr-xr-x 1 ... 4096     0 Jan 27 11:41 intellij/
drwxr-xr-x 1 ... 4096     0 Jan 27 11:41 pmd/
drwxr-xr-x 1 ... 4096     0 Jan 27 11:41 pycharm/
drwxr-xr-x 1 ... 4096     0 Jan 27 11:41 repositories/
drwxr-xr-x 1 ... 4096     0 Jan 27 11:41 sonarqube/
drwxr-xr-x 1 ... 4096     0 Jan 27 11:41 templates/
drwxr-xr-x 1 ... 4096     0 Jan 27 11:41 vscode/
-rw-r--r-- 1 ... 4096  1146 Jan 27 11:41 welcome.txt
drwxr-xr-x 1 ... 4096     0 Jan 27 11:41 workspace/
drwxr-xr-x 1 ... 4096     0 Jan 27 11:42 ./
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by HenokLachmann**
### Implemented changes:
When the `.git` folder in the settings repo is deleted, `ide update` will prompt for reinitialization. If the user confirms, the current settings directory is backed up before removal and then reinitialized.

---

## Checklist for this PR

Make sure everything is checked before merging this PR. For further info please also see
our [DoD](https://github.com/devonfw/IDEasy/blob/main/documentation/contributing/DoD.adoc).

- [x] When running `mvn clean test` locally all tests pass and build is successful
- [x] PR title is of the form `#«issue-id»: «brief summary»` (e.g. `#921: fixed setup.bat`). If no issue ID exists, title only.
- [x] PR top-level comment summarizes what has been done and contains link to addressed issue(s)
- [x] PR and issue(s) have suitable labels
- [x] Issue is set to `In Progress` and assigned to you *or* there is no issue (might happen for very small PRs)
- [x] You followed all [coding conventions](https://github.com/devonfw/IDEasy/blob/main/documentation/coding-conventions.adoc)
- [x] You have added the issue implemented by your PR in [CHANGELOG.adoc](https://github.com/devonfw/IDEasy/blob/main/CHANGELOG.adoc) unless issue is labeled
  with `internal`

### CODE REVIEW

**Review by areinicke — APPROVED** [review]
Looks good. I have confirmed it works.

File: cli/src/main/java/com/devonfw/tools/ide/git/GitContext.java [hunk 1]
```diff
@@ -61,6 +61,14 @@ public interface GitContext {
    */
   boolean fetchIfNeeded(Path repository, String remoteName, String branch);
 
+  /**
+   * Checks if the given `repository` is a valid Git repository.
+   *
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/git/GitContext.java]: The variable is not named `repository` but `directory`.
You can rename it or the easiest way to to just remove this since it is redundant to what the `@return` is already saying.

```suggestion
```

File: cli/src/main/java/com/devonfw/tools/ide/commandlet/AbstractUpdateCommandlet.java [hunk 2]
```diff
@@ -175,7 +175,7 @@ private void updateSettingsInStep() {
     Path settingsPath = this.context.getSettingsPath();
     GitContext gitContext = this.context.getGitContext();
     // here we do not use pullOrClone to prevent asking a pointless question for repository URL...
-    if (Files.isDirectory(settingsPath) && !this.context.getFileAccess().isEmptyDir(settingsPath)) {
+    if (Files.isDirectory(settingsPath) && this.context.getGitContext().isGitRepo(settingsPath)) {
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/commandlet/AbstractUpdateCommandlet.java]: The question is what this `isGitRepo` method should actually tell us.
However, with its current implementation it just checks if this is the root of a git repository that contains the `.git` folder.

As I tried to explain when you started the story we also have the `--code` repository feature.
https://github.com/devonfw/IDEasy/blob/2a5e160348d61c69e2332c3b94475f36f274bbdb/documentation/settings.adoc#code-repository

IMHO you broke this feature since in that case there will be no `.git` folder in `settings`.
Also if you do this change, the additional `Files.isDirectory(settingsPath.resolve(GitContext.GIT_FOLDER))` will always be true and does not make sense any more.

File: cli/src/main/java/com/devonfw/tools/ide/commandlet/AbstractUpdateCommandlet.java [hunk 3]
```diff
@@ -187,6 +187,21 @@ private void updateSettingsInStep() {
...
+          this.context.askForInput(
+            "Your settings repository can be updated, but this will override local changes. The "
+            + "settings contents will be backed up. Do you want to proceed?",
+            "Y/n"
+          );
+
+        if (answer.toLowerCase().equals("n")) {
+          return;
+        }
+
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/commandlet/AbstractUpdateCommandlet.java]: This is not entirely correct.
If the user enters `no` or `maybe`, you code will proceed and not abort or ask again.
Further, you are providing `Y/n` as `defaultValue` what also does not seem to make sense.

```suggestion
          this.context.askToContinue(
            "Your settings repository can be updated, but this will override local changes. The "
            + "settings contents will be backed up. Do you want to proceed?");
```

**Review by hohwille — APPROVED** [review]
@HenokLachmann thanks for your PR. I like that you extracted this `isGitRepo` method to `GitContext` following separation-of-concerns pattern and make things more explicit and expressive. 👍 Maybe we should search references for `GitContext.GIT_FOLDER` in our code-base and replace all such checks with the new method.

However, your current implementation of the story is not entirely correct.
I added some review comments to clarify. Please have a look.

File: cli/src/main/java/com/devonfw/tools/ide/commandlet/AbstractUpdateCommandlet.java (hunk 2 above)
Comment (HenokLachmann) [reply cli/src/main/java/com/devonfw/tools/ide/commandlet/AbstractUpdateCommandlet.java]: Concerning the symlink/junction case, doesn't line `AbstractUpdateCommandlet:100` check for this and does not call the method here in case of a linked settings repo?

File: cli/src/main/java/com/devonfw/tools/ide/commandlet/AbstractUpdateCommandlet.java [hunk 4]
```diff
@@ -187,6 +187,15 @@ private void updateSettingsInStep() {
         LOG.info("Skipping git pull in settings due to code repository. Use --force-pull to enforce pulling.");
       }
     } else {
+      if (!this.context.getFileAccess().isEmptyDir(settingsPath)) {
+        this.context.askToContinue(
+          "Your settings repository can be updated, but this will override local changes. The "
+          + "settings contents will be backed up. Do you want to proceed?"
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/commandlet/AbstractUpdateCommandlet.java]:
```suggestion
          "Your settings repository seems to be broken ('.git' folder not present). We can fix this by moving "
          + " your settings the backed up. You will be asked for the settings git URL and your settings will be cloned from scratch. Do you want to proceed?"
```

**Review by hohwille — APPROVED** [review]
@HenokLachmann thanks for your update. 👍
Ready for merge now.

**Comment by hohwille** [comment]
Retested with 2026.05.001-05_19_03-SNAPSHOT.
IMHO this PR broke IDEasy causing bug #1955 
Since we have filed the bug issue, I will set QA label here to mark the PR as tested.
