### PR TITLE
#1665: Separate OSType and Architecture detection in Integration tests.

### LINKED ISSUE #1665: Separate OS and architecture in integration tests
### Task summary

See (resolved) review discussion in PR #1657 
```
 local osType
  case "$OSTYPE" in
    msys*|cygwin*|win32*)
      osType="windows-x64"
```

This is actually wrong. I tested this on Windows@ARM64 and it gives me `windows-x64`.
However, the architecture does not seem to matter in any of our integration tests.
IMHO this is somehow coming from the replaced `MATRIX_OS`.
I would suggest that we simply remove the architecture since the method names are only about the operating system: `doGetOsType`, `doIsWindows`, `doIsMacOs`.
If we later need a separation by architecture, we can add another function for that.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by satorus**
### Implemented changes:

* Split OSType and Architecture detection into two separate functions in the all-tests-functions.sh file
* combine OSType and architecture to generate valid download url 
* Added detection for linux-x64,linux-arm64, mac-x64,mac-arm64, windows-x64, and windows-arm64

---

## Checklist for this PR

Make sure everything is checked before merging this PR. For further info please also see
our [DoD](https://github.com/devonfw/IDEasy/blob/main/documentation/contributing/DoD.adoc).

- [x] When running `mvn clean test` locally all tests pass and build is successful
- [x] PR title is of the form `#«issue-id»: «brief summary»` (e.g. `#921: fixed setup.bat`). If no issue ID exists, title only.
- [x] PR top-level comment summarizes what has been done and contains link to addressed issue(s)
- [x] PR and issue(s) have suitable labels
- [x] Issue is set to `In Progress` and assigned to you *or* there is no issue (might happen for very small PRs)
- [x] You followed all [coding conventions](https://github.com/devonfw/IDEasy/blob/main/documentation/coding-conventions.adoc)
- [x] You have added the issue implemented by your PR in [CHANGELOG.adoc](https://github.com/devonfw/IDEasy/blob/main/CHANGELOG.adoc) unless issue is labeled
  with `internal`

### CODE REVIEW

File: cli/src/test/all-tests-functions.sh [hunk 1]
```diff
@@ -55,28 +56,85 @@ function doGetOsType() {
...
       echo "Unknown OSTYPE: $OSTYPE. Falling back to windows (most common developer machine)." >&2
-      osType="windows-x64"
+      osType="windows"
       ;;
   esac
   echo "Detected OS type: ${osType}" >&2
   echo "$osType"
 }
 
+doGetArchNameForOs() {
```
Comment (laert-ll) [inline cli/src/test/all-tests-functions.sh]: For consistency, it would look cleaner to also include the function definition here.


```suggestion
function doGetArchNameForOs() {
```

File: cli/src/test/all-tests-functions.sh [hunk 2]
```diff
@@ -44,7 +44,8 @@ function doDownloadRelease () {
     # Change OS type based on github workflow matrix.os name
     local osType
     osType=$(doGetOsType)
-    url=$(grep "href=\"https://.*${osType}.tar.gz" "$pageHtmlLocal" | grep -o "https://[^\"]*${osType}.tar.gz" | head -1)
+    architecture=$(doGetArchNameForOs "$osType")
```
Comment (laert-ll) [inline cli/src/test/all-tests-functions.sh]: Since `osType` right above it is local, it would be best to do the same here for consistency to avoid leaking the variable into the outer scope.


```suggestion
    local architecture=$(doGetArchNameForOs "$osType")
```

File: cli/src/test/all-tests-functions.sh [hunk 3]
```diff
@@ -44,7 +44,8 @@ function doDownloadRelease () {
...
+    url=$(grep "href=\"https://.*${osType}-${architecture}.tar.gz" "$pageHtmlLocal" | grep -o "https://[^\"]*${osType}-${architecture}.tar.gz" | head -1)
```
Comment (laert-ll) [inline cli/src/test/all-tests-functions.sh:48]: If grep finds no match, $url ends up empty and curl gets called with a blank argument, which is why it might be better to include a more explicit error message in that case.

```suggestion
    url=$(grep "href=\"https://.*${osType}-${architecture}.tar.gz" "$pageHtmlLocal" | grep -o "https://[^\"]*${osType}-${architecture}.tar.gz" | head -1)
    if [ -z "$url" ]; then
      doError "No release found for ${osType}-${architecture}"
      exit 1
    fi
```

**Review by laert-ll — APPROVED** [review]
Great work! Splitting OS and architecture detection into two functions makes the code much cleaner and easier to maintain. I left a couple of minor suggestions (mostly aesthetic), but overall everything works great! 🥳

File: cli/src/test/all-tests-functions.sh [hunk 4]
```diff
@@ -55,28 +60,85 @@ function doGetOsType() {
...
+      machine="$(uname -m 2>/dev/null || echo "")"
+      case "$machine" in
+        arm64|aarch64)
+          echo "arm64"
+          ;;
+        x86_64|amd64)
+          echo "x64"
+          ;;
+        *)
+          echo "Unknown architecture from uname -m: '$machine' (osType=$osType). Falling back to x64." >&2
```
Comment (hohwille) [inline cli/src/test/all-tests-functions.sh:95]: nice logging trick to write on std-err so `$(doGetArchNameForOs "$osType")` will only get the next lines output. 👍

File: cli/src/test/all-tests-functions.sh [hunk 5]
```diff
@@ -55,28 +60,85 @@ function doGetOsType() {
...
+          echo "x64"
+          ;;
+      esac
+      ;;
+
+    windows)
+      # Prefer Windows-native environment variables (more reliable than uname in Git Bash/MSYS/Cygwin).
+      # Normalize to lower-case for comparisons.
+      archEnv="$(printf '%s' "${PROCESSOR_ARCHITECTURE:-}" | tr '[:upper:]' '[:lower:]')"
+      archWow="$(printf '%s' "${PROCESSOR_ARCHITEW6432:-}" | tr '[:upper:]' '[:lower:]')"
```
Comment (hohwille) [inline cli/src/test/all-tests-functions.sh]: After getting your intention I suggest this simplification:
```suggestion
      archEnv="${PROCESSOR_ARCHITECTURE,,}"
      archWow=${PROCESSOR_ARCHITEW6432,,}"
```

**Review by hohwille — APPROVED** [review]
@satorus thanks for your PR. Nice work 👍 
I left a comment for improvement. If you agree, just button to apply the suggestion.
