### PR TITLE
#1584: improve commandlet error handling and bash array syntax warning

### LINKED ISSUE #1584: IllegalArgumentException on ide update
### Actual behavior

I am trying to run `ide update` after configured customer repositories to be cloned automatically. I am getting an IllegalArgumentException although afterwards repository cloning is continued as expected. But seems no software updates are done at all.

```
$ ide update
Start: update (pull) settings repository
Successfully ended step 'update (pull) settings repository'.
Start: Copy configuration templates
Successfully ended step 'Copy configuration templates'.
Start: Install or update software
java.lang.IllegalArgumentException: The commandlet  could not be found!
java.lang.IllegalArgumentException: The commandlet  could not be found!
        at com.devonfw.tools.ide.commandlet.CommandletManager.getRequiredCommandlet(CommandletManager.java:52)
        at com.devonfw.tools.ide.commandlet.CommandletManager.getRequiredToolCommandlet(CommandletManager.java:77)
        at com.devonfw.tools.ide.commandlet.AbstractUpdateCommandlet.doUpdateSoftwareStep(AbstractUpdateCommandlet.java:287)
        at com.devonfw.tools.ide.commandlet.AbstractUpdateCommandlet.lambda$updateSoftware$2(AbstractUpdateCommandlet.java:267)
        at com.devonfw.tools.ide.step.Step.run(Step.java:230)
        at com.devonfw.tools.ide.step.Step.run(Step.java:219)
        at com.devonfw.tools.ide.commandlet.AbstractUpdateCommandlet.updateSoftware(AbstractUpdateCommandlet.java:267)
        at com.devonfw.tools.ide.commandlet.AbstractUpdateCommandlet.run(AbstractUpdateCommandlet.java:93)
        at com.devonfw.tools.ide.commandlet.UpdateCommandlet.run(UpdateCommandlet.java:30)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:1144)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:1054)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:95)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:59)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:133)
        at java.base@23.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)

Step 'Install or update software' ended with failure.
```

### Reproduce

Not sure yet, I installed following tools:

```
IDE_TOOLS=(java, maven, python, node)

JAVA_VERSION=21*
MVN_VERSION=3.9.9
PYTHON_VERSION=3.10*
INTELLIJ_VERSION=2025.2
INTELLIJ_EDITION=ultimate
CREATE_START_SCRIPTS=intellij,eclipse,vscode
```

### Expected behavior

Software updates are done properly and I don't get any error on `ide update` which is non-speaking.

### IDEasy status

```bash
$ ide -p status
IDE_ROOT is set to D:/projects
IDE_HOME is set to D:/projects/project
You are online.
Your settings are up-to-date.
Your version of IDEasy is 2025.10.002.
Your are using the latest version of IDEasy and no update is available.
Your operating system is windows(10.0)@x64 [Windows 11@amd64]
Successfully completed ide (status)
```

### Related/Dependent issues

_No response_

### Comments/Hints

_No response_

### PR DESCRIPTION
**Pull request by maybeec**
### Implemented changes:

This PR addresses issue #1584 where `ide update` was throwing `IllegalArgumentException: The commandlet could not be found!` with empty commandlet names.

**Root Cause Analysis:**
The issue was caused by improper bash array syntax in `IDE_TOOLS=(java, maven, python, node)`. The commas in the bash array caused the values to be parsed with trailing commas (e.g., `"java,"`, `"maven,"`), which then resulted in empty commandlet names after trimming.

**Changes Implemented:**

1. **Improved Error Messages** - Enhanced `CommandletManager` to display empty/blank commandlet names as `<empty>` in error messages for better clarity

2. **Bash Array Syntax Warning** - Added warning detection in `VariableLine.parseArray()` to alert users when commas are detected in bash array syntax:
   ```
   Detected comma in bash array. Bash array syntax uses whitespace as separator, not commas.
   Please use format like 'IDE_TOOLS=(java maven python)' instead of 'IDE_TOOLS=(java, maven, python)'.
   ```

3. **Graceful Error Handling** - Changed exception handling from throwing `IllegalArgumentException` to returning `null`:
   - Modified `CommandletManager.getRequiredCommandlet()` and `getRequiredToolCommandlet()` to return `null` instead of throwing exceptions
   - Added null checks with specific error logging in:
     - `AbstractUpdateCommandlet.doUpdateSoftwareStep()` - for IDE_TOOLS configuration
     - `RepositoryCommandlet.buildRepository()` - for build_cmd tool references
     - `RepositoryCommandlet.importRepository()` - for IDE imports configuration

4. **Performance Optimization** - Optimized `VariableLine.parseArray()` to check for commas once before the loop using `csv.contains(",")` instead of checking each item

5. **Test Coverage** - Added `testIdeToolsWithCommasInBashArray()` test to verify warning behavior when improper bash array syntax is used

**User Experience Improvements:**
- Users now see helpful error messages pointing to the specific misconfigured tool or IDE
- Users are warned about improper bash array syntax (only once per array)
- `ide update` continues processing even when individual tools cannot be found
- Error messages include configuration location hints (e.g., "Please check your IDE_TOOLS configuration")

---

## Checklist for this PR

Make sure everything is checked before merging this PR. For further info please also see
our [DoD](https://github.com/devonfw/IDEasy/blob/main/documentation/DoD.adoc).

- [x] When running `mvn clean test` locally all tests pass and build is successful
- [x] PR title is of the form `#«issue-id»: «brief summary»` (e.g. `#921: fixed setup.bat`). If no issue ID exists, title only.
- [x] PR top-level comment summarizes what has been done and contains link to addressed issue(s)
- [x] PR and issue(s) have suitable labels
- [x] Issue is set to `In Progress` and assigned to you *or* there is no issue (might happen for very small PRs)
- [x] You followed all [coding conventions](https://github.com/devonfw/IDEasy/blob/main/documentation/coding-conventions.adoc)
- [x] You have added the issue implemented by your PR in [CHANGELOG.adoc](https://github.com/devonfw/IDEasy/blob/main/CHANGELOG.adoc) unless issue is labeled
  with `internal`

### CODE REVIEW

File: cli/src/main/java/com/devonfw/tools/ide/commandlet/AbstractUpdateCommandlet.java [hunk 1]
```diff
@@ -284,7 +284,13 @@ private void doUpdateSoftwareStep(Step step) {
     List<String> regularTools = IdeVariables.IDE_TOOLS.get(this.context);
     if (regularTools != null) {
       for (String regularTool : regularTools) {
-        toolCommandlets.add(this.context.getCommandletManager().getRequiredToolCommandlet(regularTool));
+        ToolCommandlet toolCommandlet = this.context.getCommandletManager().getRequiredToolCommandlet(regularTool);
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/commandlet/AbstractUpdateCommandlet.java]:
```suggestion
        ToolCommandlet toolCommandlet = this.context.getCommandletManager().getToolCommandlet(regularTool);
```

File: cli/src/main/java/com/devonfw/tools/ide/commandlet/CommandletManager.java [hunk 2]
```diff
@@ -42,16 +42,11 @@ public interface CommandletManager {
...
+   * @return the requested {@link Commandlet} or {@code null} if not found.
    */
   default Commandlet getRequiredCommandlet(String name) {
 
-    Commandlet commandlet = getCommandlet(name);
-    if (commandlet == null) {
-      throw new IllegalArgumentException("The commandlet " + name + " could not be found!");
-    }
-    return commandlet;
+    return getCommandlet(name);
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/commandlet/CommandletManager.java]: Please revert including JavaDoc changes. It does not make sense to duplicate `getCommandlet(String)` method.
Too much AI vibe coding?
```suggestion
    Commandlet commandlet = getCommandlet(name);
    if (commandlet == null) {
      throw new IllegalArgumentException("The commandlet " + name + " could not be found!");
    }
    return commandlet;
```

File: cli/src/main/java/com/devonfw/tools/ide/git/repository/RepositoryCommandlet.java [hunk 3]
```diff
@@ -178,7 +183,10 @@ private void importRepository(RepositoryConfig repositoryConfig, Path repository
       Step step = this.context.newStep("Importing repository " + repositoryId + " into " + ide);
       step.run(() -> {
         ToolCommandlet commandlet = this.context.getCommandletManager().getRequiredToolCommandlet(ide);
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/git/repository/RepositoryCommandlet.java]: The method `getRequiredXXX` implies that we `require` the result and expect an exception if it was not found.
Please keep this coding style as you can see that you otherwise break existing other code.

```suggestion
        ToolCommandlet commandlet = this.context.getCommandletManager().getToolCommandlet(ide);
```
