### PR TITLE
#1514: Fix npm prefix not set

### LINKED ISSUE #1514: npm broken due to prefix option
### Actual behavior

```
ide install ng
...
Running command 'D:\projects\IDEasy\software\npm\bin\npm.cmd' with arguments 'install' '-g' '@angular/cli@21.0.0-next.5' '--prefix' 'D:\projects\IDEasy\software\node' ...
node:internal/modules/cjs/loader:1386
  throw err;
  ^

Error: Cannot find module 'D:\projects\IDEasy\software\npm\bin\node_modules\npm\bin\npm-prefix.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at Function._load (node:internal/modules/cjs/loader:1192:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.20.0
node:internal/modules/cjs/loader:1386
  throw err;
  ^

Error: Cannot find module 'D:\projects\IDEasy\software\npm\bin\node_modules\npm\bin\npm-cli.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at Function._load (node:internal/modules/cjs/loader:1192:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.20.0
Running command 'D:\projects\IDEasy\software\npm\bin\npm.cmd' with arguments 'install' '-g' '@angular/cli@21.0.0-next.5' '--prefix' 'D:\projects\IDEasy\software\node'
failed with exit code 1!
Step 'ide' ended with failure.
ide (install,ng) failed after PT1.936S

Running command 'D:\projects\IDEasy\software\npm\bin\npm.cmd' with arguments 'install' '-g' '@angular/cli@21.0.0-next.5' '--prefix' 'D:\projects\IDEasy\software\node'
failed with exit code 1!

Error: IDEasy failed with exit code 1
```

### Reproduce

ide install ng

### Expected behavior

Command should work without error.

### IDEasy status

```bash
IDE_ROOT is set to D:/projects
IDE_HOME is set to D:/projects/project
You are online.
Your settings are up-to-date.
Your version of IDEasy is 2025.09.001-09_29_13-SNAPSHOT.
You are using a SNAPSHOT version of IDEasy. For stability consider switching to a stable release via 'ide upgrade --mode=stable'
Your version of IDEasy is 2025.09.001-09_29_13-SNAPSHOT but version 2025.07.001-20250723.025205-3 is available. Please run the following command to upgrade to the latest version:
ide upgrade
Your operating system is windows(10.0)@x64 [Windows 11@amd64]
Successfully completed ide (status)
```

### Related/Dependent issues

#1513

### Comments/Hints

_No response_

### PR DESCRIPTION
**Pull request by jan-vcapgemini**
### Implemented changes:

* moved postInstall overwrite from Npm to Node
* added extra check to tests for set prefix success message

---

## Checklist for this PR

Make sure everything is checked before merging this PR. For further info please also see
our [DoD](https://github.com/devonfw/IDEasy/blob/main/documentation/DoD.adoc).

- [x] When running `mvn clean test` locally all tests pass and build is successful
- [x] PR title is of the form `#«issue-id»: «brief summary»` (e.g. `#921: fixed setup.bat`). If no issue ID exists, title only.
- [x] PR top-level comment summarizes what has been done and contains link to addressed issue(s)
- [x] PR and issue(s) have suitable labels
- [x] Issue is set to `In Progress` and assigned to you *or* there is no issue (might happen for very small PRs)
- [x] You followed all [coding conventions](https://github.com/devonfw/IDEasy/blob/main/documentation/coding-conventions.adoc)
- [x] You have added the issue implemented by your PR in [CHANGELOG.adoc](https://github.com/devonfw/IDEasy/blob/main/CHANGELOG.adoc) unless issue is labeled
  with `internal`

### CODE REVIEW

File: cli/src/main/java/com/devonfw/tools/ide/tool/node/Node.java [hunk 1]
```diff
@@ -23,6 +25,16 @@ public Node(IdeContext context) {
     super(context, "node", Set.of(Tag.JAVA_SCRIPT, Tag.RUNTIME));
   }
 
+  @Override
+  protected void postInstall() {
+    super.postInstall();
+    Npm npm = this.context.getCommandletManager().getCommandlet(Npm.class);
+    ProcessResult result = npm.runPackageManager("config", "set", "prefix", getToolPath().toString());
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/tool/node/Node.java]: could this cause a cyclic dependency since `npm` depends on `node` and here we depend from `node` on `npm`?

Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/tool/node/Node.java]: OK. Let's be optimistic and try it out.
