### PR TITLE
#557: fix json mapping

### LINKED ISSUE #557: Failed to update tomcat:  Cannot find a (Map) Key deserializer for type [simple type, class com.devonfw.tools.ide.version.VersionRange]
```
Start: Install tomcat
Step 'Install or update software' ended with failure.
Step 'ide (update)' failed: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot find a (Map) Key deserializer for type [simple type, class com.devonfw.tools.ide.version.VersionRange]
 at [Source: (BufferedReader); line: 1, column: 1]
 Step 'Install or update software' failed: null
  Step 'Install tomcat (*)' failed: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot find a (Map) Key deserializer for type [simple type, class com.devonfw.tools.ide.version.VersionRange]
 at [Source: (BufferedReader); line: 1, column: 1]
3 step(s) failed out of 12 steps.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/ide/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=RuntimeException%3A+com.fasterxml.jackson.databind.exc.InvalidDefinitionException%3A+Cannot+find+a+%28Map%29+Key+deserializer+for+type+%5Bsimple+type%2C+class+com.devonfw.tools.ide.version.VersionRange%5D%0A+at+%5BSource%3A+%28BufferedReader%29%3B+line%3A+1%2C+column%3A+1%5D
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot find a (Map) Key deserializer for type [simple type, class com.devonfw.tools.ide.version.VersionRange]
 at [Source: (BufferedReader); line: 1, column: 1]
        at com.devonfw.tools.ide.tool.Dependency.readJson(Dependency.java:75)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installDependencies(LocalToolCommandlet.java:357)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:160)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:144)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:132)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstall(LocalToolCommandlet.java:77)
        at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:180)
        at com.devonfw.tools.ide.commandlet.AbstractUpdateCommandlet.updateSoftware(AbstractUpdateCommandlet.java:170)
        at com.devonfw.tools.ide.commandlet.AbstractUpdateCommandlet.run(AbstractUpdateCommandlet.java:52)
        at com.devonfw.tools.ide.commandlet.UpdateCommandlet.run(UpdateCommandlet.java:29)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:902)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:830)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:88)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:51)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:28)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot find a (Map) Key deserializer for type [simple type, class com.devonfw.tools.ide.version.VersionRange]
 at [Source: (BufferedReader); line: 1, column: 1]
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1909)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._handleUnknownKeyDeserializer(DeserializerCache.java:603)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findKeyDeserializer(DeserializerCache.java:168)
        at com.fasterxml.jackson.databind.DeserializationContext.findKeyDeserializer(DeserializationContext.java:675)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.createContextual(MapDeserializer.java:314)
        at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:861)
        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:653)
        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4861)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4731)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3698)
        at com.devonfw.tools.ide.tool.Dependency.readJson(Dependency.java:72)
        ... 15 more


Error: IDEasy failed with exit code 255
```

### PR DESCRIPTION
**Pull request by hohwille**
fixes #557

### CODE REVIEW

File: cli/src/main/java/com/devonfw/tools/ide/version/VersionIdentifier.java [hunk 1]
```diff
@@ -205,7 +205,9 @@ public String toString() {
    */
   public static VersionIdentifier of(String version) {
 
-    if (version.equals("latest")) {
+    if (version == null) {
```
Comment (jan-vcapgemini) [inline cli/src/main/java/com/devonfw/tools/ide/version/VersionIdentifier.java:208]: What about empty versions? Possible at all?

**Review by jan-vcapgemini — APPROVED** [review]
LGTM. Added a short question.

File: cli/src/main/java/com/devonfw/tools/ide/version/VersionIdentifier.java (hunk 1 above)
Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/version/VersionIdentifier.java:208]: empty String results in `null` because `VersionSegment.of("")` return `null`.
Can we close this review comment?
If you have questions it is better to ask via chat than gitub review comment.

**Review by slskiba — APPROVED** [review]
LGTM :+1:

Since you created the `json` package, it might be plausible to also move the `JsonObject` and `JsonVersionItem` classes there. Even though they are not functionally connected , those two classes currently lie in `common`, and `json` just seems like the better choice here.

**Comment by hohwille** [comment]
> Since you created the json package, it might be plausible to also move the JsonObject and JsonVersionItem classes there. Even though they are not functionally connected , those two classes currently lie in common, and json just seems like the better choice here.

Done.
