### PR TITLE
#1346: Fix ide upgrade throwing exception when offline

### LINKED ISSUE #1346: ide upgrade throws exception when offline
### Actual behavior

When running ide upgrade without an internet connection an exception is being thrown.

```
<username>@Mac-mini ~ % ide upgrade --mode=snapshot
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/IDEasy/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Failed+to+fetch+XML+metadata+from+https%3A%2F%2Fs01.oss.sonatype.org%2Fcontent%2Frepositories%2Fsnapshots%2Fcom%2Fdevonfw%2Ftools%2FIDEasy%2Fide-cli%2Fmaven-metadata.xml
java.lang.IllegalStateException: Failed to fetch XML metadata from https://s01.oss.sonatype.org/content/repositories/snapshots/com/devonfw/tools/IDEasy/ide-cli/maven-metadata.xml
	at com.devonfw.tools.ide.tool.repository.MavenRepository.fetchXmlMetadata(MavenRepository.java:313)
	at com.devonfw.tools.ide.tool.repository.MavenRepository.fetchVersions(MavenRepository.java:215)
	at com.devonfw.tools.ide.tool.repository.MavenRepository.resolveVersion(MavenRepository.java:202)
	at com.devonfw.tools.ide.tool.repository.MavenRepository.resolveVersion(MavenRepository.java:187)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:187)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:169)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstallStep(LocalToolCommandlet.java:89)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.install(LocalToolCommandlet.java:79)
	at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:262)
	at com.devonfw.tools.ide.tool.IdeasyCommandlet.install(IdeasyCommandlet.java:112)
	at com.devonfw.tools.ide.commandlet.UpgradeCommandlet.run(UpgradeCommandlet.java:43)
	at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:988)
	at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:897)
	at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:95)
	at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:59)
	at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:133)
	at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.net.UnknownHostException: s01.oss.sonatype.org
	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base@21.0.2/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base@21.0.2/java.net.Socket.connect(Socket.java:751)
	at java.base@21.0.2/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base@21.0.2/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:181)
	at java.base@21.0.2/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base@21.0.2/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base@21.0.2/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base@21.0.2/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at java.base@21.0.2/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
	at java.base@21.0.2/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base@21.0.2/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
	at java.base@21.0.2/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
	at java.base@21.0.2/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base@21.0.2/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
	at java.base@21.0.2/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
	at java.base@21.0.2/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
	at java.base@21.0.2/java.net.URL.openStream(URL.java:1325)
	at com.devonfw.tools.ide.tool.repository.MavenRepository.fetchXmlMetadata(MavenRepository.java:309)
	... 16 more


Error: IDEasy failed with exit code 255
```

### Reproduce

1. Disconnect from the internet
2. Run `ide upgrade`

### Expected behavior

IDEasy should tell the user that he is offline and not throw a huge exception.

### IDEasy status

```bash
IDE_ROOT is set to /Users/<username>/projects
You are not inside an IDE project: /Users/<username>
You are online.
Your version of IDEasy is 2025.05.002-05_28_09-SNAPSHOT but version 2025.05.002-20250528.092756-7 is available. Please run the following command to upgrade to the latest version:
ide upgrade
Your operating system is mac(10.15.7)@x64 [Mac OS X@amd64]
Successfully completed ide (status)
```

### Related/Dependent issues

_No response_

### Comments/Hints

_No response_

### PR DESCRIPTION
**Pull request by juliane-cap**
### Implemented changes:

* Add check to see if online before trying to perform ide upgrade
* Add a Test for this functionality

---

## Checklist for this PR

Make sure everything is checked before merging this PR. For further info please also see
our [DoD](https://github.com/devonfw/IDEasy/blob/main/documentation/DoD.adoc).

- [x] When running `mvn clean test` locally all tests pass and build is successful
- [x] PR title is of the form `#«issue-id»: «brief summary»` (e.g. `#921: fixed setup.bat`). If no issue ID exists, title only.
- [x] PR top-level comment summarizes what has been done and contains link to addressed issue(s)
- [x] PR and issue(s) have suitable labels
- [x] Issue is set to `In Progress` and assigned to you *or* there is no issue (might happen for very small PRs)
- [x] You followed all [coding conventions](https://github.com/devonfw/IDEasy/blob/main/documentation/coding-conventions.adoc)
- [x] You have added the issue implemented by your PR in [CHANGELOG.adoc](https://github.com/devonfw/IDEasy/blob/main/CHANGELOG.adoc) unless issue is labeled
  with `internal`

### CODE REVIEW

**Review by hohwille — APPROVED** [review]
@juliane-cap thanks for your PR. Nice and easy fix including a solid test. Great work👍 
Looks slightly related to #1371 ;)
Ready for merge.

File: cli/src/main/java/com/devonfw/tools/ide/tool/IdeasyCommandlet.java [hunk 1]
```diff
@@ -106,6 +106,11 @@ public Path getToolPath() {
   @Override
   public boolean install(boolean silent) {
 
+    if (!this.context.isOnline()) {
+      this.context.warning("You are offline. IDEasy requires an internet connection to upgrade - skipping upgrade.");
+      return false;
+    }
+
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/tool/IdeasyCommandlet.java:113]:
```suggestion
this.context.requireOnline("upgrade of IDEasy");
```

Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/tool/IdeasyCommandlet.java:113]: We should throw a `CliOfflineException` instead of logging a warning and ending with success if there was actually an error.
As the name of the method `requireOnline` suggests that I am required to be online, I was wrong with my suggestion.
Thanks for pointing that out.
Since that method is already used in other places we cannot simply change its implementation accordingly.
However, it would be smart to add a new optional boolean parameter to `requireOnline` that allows us to specify if we want to trigger an explicit `isOnline()` check or keep the existing behaviour.

Comment (juliane-cap) [reply cli/src/main/java/com/devonfw/tools/ide/tool/IdeasyCommandlet.java]: I’ve implemented the change by adding a boolean parameter `explicitOnlineCheck` to `requireOnline()` that allows triggering an explicit `isOffline()` check, while keeping the existing behavior as default. I believe this reflects what was suggested, but let me know if I misunderstood anything.

I used `isOffline()` instead of `!isOnline()` to ensure it still works correctly in offline-mode.

Also updated the test to assert for the exception instead of checking for a warning log.

**Review by hohwille — APPROVED** [review]
@juliane-cap thanks for the rework. Now perfect and ready for merge.
