### PR TITLE
#520: #645: Update Changelog

### LINKED ISSUE #520: NullPointerException on GitContextImpl.retrieveRemoteAndBranchName
```
D:\projects\IDEasy>ideasy jmc
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 22: .: git-sh-setup: file not found
Running command 'C:\Program Files\Git\cmd\git.exe' with arguments '--no-pager' 'pull' '--quiet' failed with exit code 1!
  feature/tomcat-test f9e4fb3a Update urls
* master              6be248d1 [origin/master] Update urls
Step 'ide (jmc)' failed: java.lang.NullPointerException
 Step 'Install java (21*)' failed: java.lang.NullPointerException
2 step(s) failed out of 2 steps.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/ide/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=java.lang.NullPointerException
java.lang.NullPointerException
        at com.devonfw.tools.ide.context.GitContextImpl.retrieveRemoteAndBranchName(GitContextImpl.java:198)
        at com.devonfw.tools.ide.context.GitContextImpl.pull(GitContextImpl.java:186)
        at com.devonfw.tools.ide.context.GitContextImpl.pullOrClone(GitContextImpl.java:112)
        at com.devonfw.tools.ide.context.GitContextImpl.pullOrCloneIfNeeded(GitContextImpl.java:70)
        at com.devonfw.tools.ide.context.GitContextImpl.pullOrCloneAndResetIfNeeded(GitContextImpl.java:76)
        at com.devonfw.tools.ide.context.GitContext.pullOrCloneAndResetIfNeeded(GitContext.java:53)
        at com.devonfw.tools.ide.context.AbstractIdeContext.getUrls(AbstractIdeContext.java:548)
        at com.devonfw.tools.ide.repo.DefaultToolRepository.resolveVersion(DefaultToolRepository.java:35)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:157)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:144)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:132)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstall(LocalToolCommandlet.java:77)
        at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:180)
        at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:169)
        at com.devonfw.tools.ide.tool.jmc.Jmc.doInstall(Jmc.java:37)
        at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:180)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.runTool(LocalToolCommandlet.java:332)
        at com.devonfw.tools.ide.tool.jmc.Jmc.run(Jmc.java:44)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:921)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:859)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:88)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:51)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:28)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

### PR DESCRIPTION
**Pull request by WorkingAmeise**
closes #520  null pointer exception on git context impl

UPDATE: In PR #645 I accidentally fixed #520. Sorry for overlapping with this PR and your work @WorkingAmeise.
After merging the changelog entry is left that I will now merge and thereby close #520 automatically. The NPE fix will be found in #645 however.

### CODE REVIEW

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java [hunk 1]
```diff
@@ -194,9 +195,27 @@ public void pull(Path targetRepository) {
...
+        ProcessResult branchResult = this.processContext.addArg("branch").addArg("-vv").run(ProcessMode.DEFAULT_CAPTURE);
+        List<String> branches = branchResult.getOut();
+        ProcessResult repoResult = this.processContext.addArg("rev-parse").addArg("--show-toplevel").run(ProcessMode.DEFAULT_CAPTURE);
+        List<String> repoResultOut = repoResult.getOut();
+        String repository = repoResultOut.get(0);
+        repository = repository.substring(repository.lastIndexOf("/") + 1);
+
+        for (String branch : branches) {
+          if (branch.startsWith("*")) {
+            branch = branch.trim().startsWith("*") ? branch.substring(2) : branch;
```
Comment (jan-vcapgemini) [inline cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:208]: Please replace with regular if.

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java [hunk 2]
```diff
@@ -233,6 +252,9 @@ private Map<String, String> retrieveRemoteAndBranchName() {
     Map<String, String> remoteAndBranchName = new HashMap<>();
     ProcessResult remoteResult = this.processContext.addArg("branch").addArg("-vv").run(PROCESS_MODE);
     List<String> remotes = remoteResult.getOut();
+    if (remotes == null) {
+      return null;
+    }
```
Comment (jan-vcapgemini) [inline cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:257]: Would be better to return an empty Map instead of null I think.

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java [hunk 3]
```diff
@@ -194,9 +195,27 @@ public void pull(Path targetRepository) {
...
-      this.context.warning("Git pull for {}/{} failed for repository {}.", remoteAndBranchName.get("remote"), remoteAndBranchName.get("branch"),
-          targetRepository);
-      handleErrors(targetRepository, result);
+      if (remoteAndBranchName == null) {
+        ProcessResult branchResult = this.processContext.addArg("branch").addArg("-vv").run(ProcessMode.DEFAULT_CAPTURE);
+        List<String> branches = branchResult.getOut();
+        ProcessResult repoResult = this.processContext.addArg("rev-parse").addArg("--show-toplevel").run(ProcessMode.DEFAULT_CAPTURE);
+        List<String> repoResultOut = repoResult.getOut();
+        String repository = repoResultOut.get(0);
+        repository = repository.substring(repository.lastIndexOf("/") + 1);
```
Comment (jan-vcapgemini) [inline cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:204]: This logic should be moved to `retrieveRemoteAndBranchname` I think.

**Review by jan-vcapgemini — CHANGES_REQUESTED** [review]
Thanks for your additions. I've added some CRs to resolve first, then this can go into review.

**Review by jan-vcapgemini — COMMENTED** [review]
I think we also should add some tests for a better coverage of this case.

**Review by hohwille — COMMENTED** [review]
Some thoughts on this...
I created a local feature branch that has no remote branch and pulled from it:
```
$ git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> feature/556-update-path-on-pc-run


hohwille@CE49454 MSYS /d/projects/IDEasy/workspaces/main/IDEasy/documentation (feature/556-update-path-on-pc-run)
$ echo $?
1
```

Then I switched back to main, went offline and repeated the `pull`:
```
$ git pull
fatal: unable to access 'https://github.com/hohwille/IDEasy.git/': Could not resolve host: github.com

hohwille@CE49454 MSYS /d/projects/IDEasy/workspaces/main/IDEasy/documentation (main)
$ echo $?
1
```

So unfortunately we cannot use the return code of git pull to distinguish if we have no remote branch or something else went wrong.

However, if we use this complex code to run `git branch -vv` and parse all the results, we could also parse the initial error and search for `There is no tracking information for the current branch`.
However, I am unsure if git supports localization and if some user might get the output localized to a different language.
Otherwise, maybe there is a smarter way to ask git if we are on a local branch?
At least you could call `git branch -vv --contains` to get only relevant branches.
IMHO there must still be a smarter way to figure this out...

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java (hunk 1 above)
Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:208]: FYI: It does not make sense if `branch.startsWith("*")` is true to `trim` the String and then check the same condition again.
You either need to `trim` before doing the `if` check or you can check the secondary check since it must always evaluate to `true`  here and you can directly use `branch.substring(2)`. However, I am quite sure, that you actually wanted to first trim the branch (`branch = branch.trim()`) and then do the `if` check but can remove the tenary expression entirely.

**Comment by WorkingAmeise** [comment]
The tests will be submitted later via issue #620

**Review by jan-vcapgemini — APPROVED** [review]
LGTM, ready for review.

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java [hunk 4]
```diff
@@ -187,16 +187,29 @@ public void clone(GitUrl gitRepoUrl, Path targetRepository) {
   @Override
   public void pull(Path targetRepository) {
 
-    this.processContext.directory(targetRepository);
+    Optional<String[]> RemoteAndBranchOptional = getLocalRemoteAndBranch(targetRepository);
+
+    if (RemoteAndBranchOptional.isEmpty()) {
+      this.context.warning("Skipping pull!");
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:193]: The end-user will not understand this warning. You should add more contextual information.

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java [hunk 5]
```diff
@@ -187,16 +187,29 @@ public void clone(GitUrl gitRepoUrl, Path targetRepository) {
   @Override
   public void pull(Path targetRepository) {
 
-    this.processContext.directory(targetRepository);
+    Optional<String[]> RemoteAndBranchOptional = getLocalRemoteAndBranch(targetRepository);
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:190]: In Java we always name variables starting with a lower-case letter:
```suggestion
    Optional<String[]> remoteAndBranchOptional = getLocalRemoteAndBranch(targetRepository);
```

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java [hunk 6]
```diff
@@ -187,16 +187,29 @@ public void clone(GitUrl gitRepoUrl, Path targetRepository) {
...
+
     ProcessResult result;
     // pull from remote
     result = this.processContext.addArg("--no-pager").addArg("pull").addArg("--quiet").run(PROCESS_MODE);
 
     if (!result.isSuccessful()) {
-      Map<String, String> remoteAndBranchName = retrieveRemoteAndBranchName();
+      String[] RemoteAndBranch = RemoteAndBranchOptional.get();
+      String remote = RemoteAndBranch[0];
+      String branch = RemoteAndBranch[1];
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:204]: In Java we always name variables starting with a lower-case letter:
```suggestion
      String[] remoteAndBranch = remoteAndBranchOptional.get();
      String remote = remoteAndBranch[0];
      String branch = remoteAndBranch[1];
```

FYI: Nice to have but since we now use this `getLocalRemoteAndBranch` method in multiple places:
Arrays are always ugly and it gets kind of magic that `0` refers to the `remote` and `1` to `branch`.
A solution would be to create a Java `record` called `RemoteAndBranch` containing these two Strings and change `getLocalRemoteAndBranch` to return this `record` instead of an array. Then we avoid having these magic index mapping that is actually internal knowledge of the `getLocalRemoteAndBranch` outside of the method implementation and make the code more transparent.

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java [hunk 7]
```diff
@@ -187,16 +187,29 @@ public void clone(GitUrl gitRepoUrl, Path targetRepository) {
...
+      Map<String, String> remoteAndBranchName = new HashMap<>();
+      remoteAndBranchName.put("remote", remote);
+      remoteAndBranchName.put("branch", branch);
       this.context.warning("Git pull for {}/{} failed for repository {}.", remoteAndBranchName.get("remote"), remoteAndBranchName.get("branch"),
           targetRepository);
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:209]: It is pointless to create this `Map` now:
```suggestion
      this.context.warning("Git pull for {}/{} failed for repository {}.", remote, branch, targetRepository);
```

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java [hunk 8]
```diff
@@ -187,16 +187,29 @@ public void clone(GitUrl gitRepoUrl, Path targetRepository) {
...
       handleErrors(targetRepository, result);
+
+
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:212]: avoid adding these newlines.

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java [hunk 9]
```diff
@@ -265,7 +252,20 @@ private Optional<String[]> getLocalRemoteAndBranch(Path repositoryPath) {
...
+      String repository = repoResultOut.get(0);
+      repository = repository.substring(repository.lastIndexOf("/") + 1);
+      for (String branch : branches) {
+        branch = branch.trim();
+        if (branch.startsWith("*")) {
+          branch = branch.substring(2);
+          String checkedOutBranch = branch.substring(0, branch.indexOf(" "));
+          context.warning("You are on branch {} of repository {}, which has no upstream configured!", checkedOutBranch, repository);
+        }
+      }
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:268]: Great that you are trying to improve the warning message. 👍
However, this does not really look like a good improvement to me.
1. If the for `if` never matches you will print nothing anymore, if it matches multiple times, you would get multiple warnings what can be extremely confusion. Be aware that you are parsing human readable output with `-vv` that may change with newer git versions.
2. In case you want to get the current branch, why not just getting it directly via `git branch --show-current`?
3. Why do you need git to determine the current directory? So instead of `repository` just use `repositoryPath` and you can avoid calling `git` as external process.

**Review by hohwille — APPROVED** [review]
@WorkingAmeise thanks for your PR. You now figured out what is the right way to solve this issue nicely 👍 
I left some comments to rework. Please have a look. When resolved, we can merge.

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java (hunk 4 above)
Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:193]: I also just saw that a warning has already been logged by `getLocalRemoteAndBranch` if we ran into this situation.
IMHO this additional warning is not needed anymore.

**Comment by hohwille** [comment]
Build failed with this error:
```
[ERROR] Failures: 
[ERROR]   GitContextTest.testRunGitPullWithoutForce:96 
Expecting path:
  /tmp/junit6805495595980645108/.git/update
to exist (symbolic links were followed).
[INFO] 
[ERROR] Tests run: 324, Failures: 1, Errors: 0, Skipped: 0
```

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java (hunk 4 above)
Comment (WorkingAmeise) [reply cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:193]: My thought behind this was, that, since we use getLocalRemoteAndBranch in multiple places, we give the more genereal contextual information here and specify the impact on the action, the user wanted to perform in the calling method (pull int this case). Would it be better if i do the entire warning in pull?

Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:193]: I removed `getLocalRemoteAndBranch` in #645.
IMHO we can massively simplify all this...

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java (hunk 9 above)
Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:268]: See PR #645 where I added `determineCurrentBranch(Path)` and `determineRemote(Path)`.
