### PR TITLE
#1561: Fix BASH_PATH not used properly

### LINKED ISSUE #1561: IDEasy can not handle BASH_PATH variable properly
### Actual behavior

When the user sets the BASH_PATH variable in his USER environment variables to f.e. C:\customfolder\git\bin\bash.exe IDEasy does not utilize the variable and constantly reports warnings that the git bash was not found e.g. `Query to windows registry for finding bash failed with exit code`

### Reproduce

1. Download and unpack a portable version of git
2. Set the BASH_PATH to your portable git bash.exe location
3. Check if IDEasy accepted the variable and does not report errors about a missing git bash

### Expected behavior

IDEasy should uitilize the variable and not report any warnings that the git bash was not found.

### IDEasy status

```bash
Updates are available for the settings repository. If you want to apply the latest changes, call "ide update"
IDE_ROOT is set to D:\projects
IDE_HOME is set to D:\projects\release-test
You are online.
Your settings are not up-to-date, please run 'ide update'.
Your version of IDEasy is 2025.11.001-SNAPSHOT.
You are using a SNAPSHOT version of IDEasy. For stability consider switching to a stable release via 'ide upgrade --mode=stable'
Your version of IDEasy is 2025.11.001-SNAPSHOT but version 2025.11.001-20251031.024545-1 is available. Please run the following command to upgrade to the latest version:
ide upgrade
Your operating system is windows(10.0)@x64 [Windows 11@amd64]
Successfully completed ide (status)
```

### Related/Dependent issues

_No response_

### Comments/Hints

A workaround could be to only show the warning when in debug mode.

### PR DESCRIPTION
**Pull request by jan-vcapgemini**
### Implemented changes:

* optimized findBash method to check for set BASH_PATH first
* adjusted IdeContext findBashRequired exception message to be more clear and independent of Windows
* removed unnecessary extra checks in GitContextImpl verifyGitInstalled method and used result of findBashRequired instead
* applied some code reformats
* resolved git location for windows systems from git bash path and added it to context PATH
* fixed getRegistryValue method to return null if reg query failed and returned the failed message instead of the expected result
* changed findBash windows check from INSTANCE to getSystemInfo().isWindows
* changed visibility of findBashOnWindows to protected to be overwritten in tests
* added PATH separator replacement logic for tests to createSystemVariables method
* changed findBinaryInOrder OS check from INSTANCE to getSystemInfo().isWindows()
* changed SystemInfo().INSTANCE check to getSystemInfo().isWindows() in IdeContext.findBashRequired
* added check for missing bash binary as well as debug messages to GitContextImpl.verifyGitInstalled
* fixed IdeasyCommandlet.setGitLongpaths not using proper GitContext
* added overwrite of findBashRequired to AbstractIdeContext to ignore checks for git in tests
* added overwrite of verifyGitInstalled to GitContextImplMock to ignore checks for git in tests
* replaced batch code with bash in jmc cmd file
* refactored findBash method
* added findBashOnWindowsBashPath method
* added findBashOnWindowsDefaultGitPath method (extracted from findBashOnWindows)
* added findBashInPath
* renamed findBashOnWindows to findBashInWindowsRegistry
* changed findBash return type from String to Path
* refactored verifyGitInstalled
* renamed verifyGitInstalled to findGitRequired
* removed unnecessary environment.properties files in test resources
* introduced constants for git and bash not installed messages
* removed findGitRequired checks from GitContextImpl methods

---

## Checklist for this PR

Make sure everything is checked before merging this PR. For further info please also see
our [DoD](https://github.com/devonfw/IDEasy/blob/main/documentation/DoD.adoc).

- [x] When running `mvn clean test` locally all tests pass and build is successful
- [x] PR title is of the form `#«issue-id»: «brief summary»` (e.g. `#921: fixed setup.bat`). If no issue ID exists, title only.
- [x] PR top-level comment summarizes what has been done and contains link to addressed issue(s)
- [x] PR and issue(s) have suitable labels
- [x] Issue is set to `In Progress` and assigned to you *or* there is no issue (might happen for very small PRs)
- [x] You followed all [coding conventions](https://github.com/devonfw/IDEasy/blob/main/documentation/coding-conventions.adoc)
- [x] You have added the issue implemented by your PR in [CHANGELOG.adoc](https://github.com/devonfw/IDEasy/blob/main/CHANGELOG.adoc) unless issue is labeled
  with `internal`

### CODE REVIEW

File: cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java [hunk 1]
```diff
@@ -1410,10 +1410,11 @@ public String findBash() {
 
     String bash = BASH;
     if (SystemInfoImpl.INSTANCE.isWindows()) {
-      bash = findBashOnWindows();
+      String variable = IdeVariables.BASH_PATH.getName();
+      bash = getVariables().get(variable);
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java]: Create `Path` and check if exists.
Then do debug logging if exists and warning if variable is defined but points to non existing file.

File: cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java
[the remark this answers is not in the document]
Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java]: From PR #1587 

just to make out dependencies explicit:
Here we need to make use of PR #1592 and convert the `if` into a lambda filter expression including also the `"C:\Windows\System32\bash.exe"` exclusion.

I would not merge this PR unless this is included. So we have to complete and merge PR #1592 first.

File: cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java [hunk 2]
```diff
@@ -1399,15 +1400,21 @@ public String findBash() {
             Path bashPath = getPath().findBinary(plainBash, pathsToIgnore);
             bash = bashPath.toAbsolutePath().toString();
             if (bashPath.equals(plainBash)) {
-              warning("Could not find any usable bash on your PATH!");
+              warning("No usable bash executable was found in your system PATH!");
               bash = null;
+            } else {
+              debug("A proper bash executable was found in the system PATH at: {}", bash);
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java]: same here.

```suggestion
              debug("A proper bash executable was found in your PATH environment variable at: {}", bash);
```

File: cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java]: IMHO the order is still not ideal and as discussed:
1. BASH_PATH variable
2. PATH variable
3. Windows registry

Currently 2. and 3. are still flipped.

Further, the method name `findBashOnWindows` does not make sense any more.
All steps 1-3 are only done on Windows.
The method `findBashOnWindows` should be renamed to `findBashInWindowsRegistry`.
Also the code to find the bash on the `PATH` could be extracted to `findBashInPath` method to make this code more readable and the flow and order more obvious.

File: cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java [hunk 3]
```diff
@@ -257,14 +259,35 @@ IdeContext getContext() {
...
-      String message = "Git is not installed on your computer but required by IDEasy. Please download and install git:\n"
-          + "https://git-scm.com/download/";
-      throw new CliException(message);
+    String bashBinary = this.context.findBashRequired();
+    String message = "Git is not installed on your computer but required by IDEasy. Please download and install git:\n"
+        + "https://git-scm.com/download/";
+
+    if (SystemInfoImpl.INSTANCE.isWindows()) {
+      Path bashPath = Path.of(bashBinary);
+      if (Files.exists(bashPath)) {
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java]: see my comments above:
1. Already return `Path` instead of `String`
2. Return `null` if not exists on all platforms

File: cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java [hunk 4]
```diff
@@ -257,14 +259,35 @@ IdeContext getContext() {
...
+        Path gitPath = bashPath.getParent().resolve("git.exe");
+        if (Files.exists(gitPath)) {
+          this.context.trace("Git path was extracted from bash path at: {}", gitPath);
+          SystemPath systemPath = this.context.getPath();
+          systemPath.setPath("git", gitPath);
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java]: I see your point here.
However, this also seems unclean to me.
I would follow the same strategy as we have with `findBash`:
Refactor this method to:
```
public Path findGitRequired()
```
Make it use a member variable with lazy init as suggested for bash.
Change `GitContextImpl` to use this method.

I cannot think right now about a good reason why the user does not add `git` to his `PATH` himself.
IMHO users that do not have `git` on their `PATH` are not reasonable software engineers.
They should first fix their setup before using IDEasy.
However, it is great that you managed to find git on windows from the bash we found.
But should EnvironmentCommandlet temporary add git to `PATH` if the user did not do it?
Maybe he has a reason not to do it?

File: cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java
Comment (jan-vcapgemini) [reply cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java]: I've changed the order and renamed the methods as well as extracted more methods to make it more clear now.

File: cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java [hunk 5]
```diff
@@ -1399,15 +1400,21 @@ public String findBash() {
...
           }
         }
+        String message = "Could not locate bash in the Windows registry. Attempting to use the fallback from BASH_PATH";
+        if (!bashPathValid) {
+          message += ", but no valid path was provided.";
+        }
         if (bash == null) {
-          info("Could not find bash in Windows registry, using bash from {} as fallback: {}", bashPathVariableName, bash);
+          error(message);
         }
```
[the remark this answers is not in the document]
Comment (jan-vcapgemini) [reply cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java]: I've removed this message and made sure that each find* method will properly log their state now.

File: cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java (hunk 3 above)
Comment (jan-vcapgemini) [reply cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java]: Adjusted.

File: cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java [hunk 6]
```diff
@@ -162,7 +165,7 @@ public void clone(GitUrl gitUrl, Path repository) {
   @Override
   public void pull(Path repository) {
 
-    verifyGitInstalled();
+    findGitRequired();
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java]:
```suggestion
```

File: cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java [hunk 7]
```diff
@@ -245,7 +248,7 @@ public void cleanup(Path repository) {
   @Override
   public String retrieveGitUrl(Path repository) {
 
-    verifyGitInstalled();
+    findGitRequired();
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java]:
```suggestion
```

File: cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java [hunk 8]
```diff
@@ -255,17 +258,59 @@ IdeContext getContext() {
...
+        } else {
+          this.context.error("Git path: {} was extracted from bash path at: {} but it does not exist", gitPath, bashBinary);
+          return null;
+        }
+      } else {
+        this.context.error("Bash path was checked at: {} but it does not exist", bashBinary);
+        return null;
+      }
+    } else {
+      Path binaryGitPath = this.context.getPath().findBinary(gitPath);
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java]: This is the how this implementation should start after `this.git` is not initialised.
Only if `git` is not found on `PATH` we can start with our "windows hack/workaround" and also remove the code adding git to the `SystemPath`.

File: cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java [hunk 9]
```diff
@@ -66,14 +69,14 @@ public boolean isRepositoryUpdateAvailable(Path repository) {
   @Override
   public boolean isRepositoryUpdateAvailable(Path repository, Path trackedCommitIdPath) {
 
-    verifyGitInstalled();
+    findGitRequired();
```
[the remark this answers is not in the document]
Comment (jan-vcapgemini) [reply cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java]: Adjusted.

File: cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java [hunk 10]
```diff
@@ -300,9 +298,8 @@ public Path findGit() {
         return null;
       }
     } else {
-      Path binaryGitPath = this.context.getPath().findBinary(gitPath);
       if (gitPath == binaryGitPath) {
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java]: This has to go before `if (SystemInfoImpl.INSTANCE.isWindows()) {`.
So only if we did not find bash in our PATH, we can do the Windows workaround.
If it helps you again extract private method `findGitOnPath()` and `findGitOnWindowsViaBash()`.
