### PR TITLE
#1731: Fixed Solar Install returning NPE

### LINKED ISSUE #1731: Sonar Installation leads to NPE
### Actual behavior

`ide install` returns with a NullPointerException due to the `command` enum property variable being NULL in the code.

Image

Below is the stacktrace showing a typical LocalCommandlet tool installation execution path. The error happens when Sonar is both already installed, and not installed.

Image
Image

### Reproduce

Typical installation steps as per documentation
1. `icd -p ProjectName -w`
2. `ide install sonar`

### Expected behavior

Installation of the latest Sonar release (currently 26.3.0.120487)

### IDEasy status

```bash
IDE_ROOT is set to C:\Users\tabumukh\projects
IDE_HOME is set to C:\Users\tabumukh\projects\IDEasy
Your version of IDEasy is 2026.02.001.
Your are using the latest version of IDEasy and no update is available.
Your operating system is windows(10.0)@x64 [Windows 11@amd64]
You are online.
Found bash executable at: C:\Program Files\Git\usr\bin\bash.exe
Found git executable at: C:\Program Files\Git\mingw64\bin\git.exe
Your settings are up-to-date.
Successfully completed ide (status)
```

### Related/Dependent issues

_No response_

### Comments/Hints

I think this bug is mainly caused from `getBinaryName` being triggered for the variable `linkDir` during tool commandlet installation. I am not sure if we're asking for the command (START, STOP, ANALYZE) to start sonar once it's installed, but otherwise this code needs to be re-written, as we do not give a additional commands with `install sonar`

```java
 protected String getBinaryName() {

    if (this.context.getSystemInfo().isWindows()) {
      SonarCommand command = this.command.getValue();
      if (command.equals(SonarCommand.START)) {
        return "windows-x86-64/StartSonar.bat";
      } else if (command.equals(SonarCommand.STOP)) {
        return "windows-x86-64/SonarService.bat";
      }
    } else if (this.context.getSystemInfo().isMac()) {
      return "macosx-universal-64/sonar.sh";
    }
    return "linux-x86-64/sonar.sh";
  }
```

### PR DESCRIPTION
**Pull request by tmukh**
### Implemented changes:

* Changed relative path to absolute path for resolution, in order to run Sonar installation
* created comprehensive Sonar tests following the Commandlet test patterns. 
* SonarTest.java with three test methods:
* * testSonarStartCommand - Tests the Sonar commandlet with START command
* * testSonarStopCommand - Tests the Sonar commandlet with STOP command
* * testSonarAnalyzeCommand - Tests the Sonar commandlet with ANALYZE command
* Each test:
* * Creates an IDE test context for the sonar project
* * Retrieves the Sonar commandlet from the commandlet manager
* * Sets the appropriate command using the enum
* * Validates that the commandlet is properly initialized with the correct command
Structure Created:
```
src/test/resources/ide-projects/sonar/
├── project/
│   ├── home/.ide/ide.properties
│   ├── settings/ide.properties
│   └── workspaces/
├── repository/sonar/sonar/default/
│   ├── .ide.software.version
│   ├── bin/
│   │   ├── windows-x86-64/
│   │   │   ├── StartSonar.bat
│   │   │   └── SonarService.bat
│   │   ├── linux-x86-64/sonar.sh
│   │   └── macosx-universal-64/sonar.sh
│   └── conf/sonar.properties
└── _ide/urls/sonar/sonar/26.3.0.120487/urls
```

The tests follow the same pattern as the other tests, using the **@WireMockTest** annotation and **AbstractIdeContextTest** 
base class for proper test isolation and context management.

---

## Checklist for this PR

- [x] When running `mvn clean test` locally all tests pass and build is successful
- [x] PR title is of the form `#«issue-id»: «brief summary»` (e.g. `#921: fixed setup.bat`). If no issue ID exists, title only.
- [x] PR top-level comment summarizes what has been done and contains link to addressed issue(s)
- [x] PR and issue(s) have suitable labels
- [x] Issue is set to `In Progress` and assigned to you *or* there is no issue (might happen for very small PRs)
- [x] You followed all [coding conventions](https://github.com/devonfw/IDEasy/blob/main/documentation/coding-conventions.adoc)
- [x] You have added the issue implemented by your PR in [CHANGELOG.adoc](https://github.com/devonfw/IDEasy/blob/main/CHANGELOG.adoc) unless issue is labeled
  with `internal`

### CODE REVIEW

File: cli/src/main/java/com/devonfw/tools/ide/tool/sonar/Sonar.java [hunk 1]
```diff
@@ -81,20 +83,35 @@ protected void doRun() {
...
-      SonarCommand command = this.command.getValue();
-      if (command.equals(SonarCommand.START)) {
-        return "windows-x86-64/StartSonar.bat";
-      } else if (command.equals(SonarCommand.STOP)) {
+      if (command.equals(SonarCommand.STOP)) {
         return "windows-x86-64/SonarService.bat";
+
+      } else {
+        return "windows-x86-64/StartSonar.bat";
       }
```
[the remark this answers is not in the document]
Comment (tmukh) [reply cli/src/main/java/com/devonfw/tools/ide/tool/sonar/Sonar.java]: The trick was to use newContext(PROJECT_NAME) without the WireMockRuntimeInfo parameter. This makes the test use the local repository files directly instead of trying to download via WireMock, which is exactly what we needed!

File: cli/src/test/java/com/devonfw/tools/ide/tool/sonar/SonarTest.java [hunk 2]
```diff
@@ -0,0 +1,210 @@
...
+  /**
+   * Tests the {@link Sonar} commandlet initialization with ANALYZE command.
+   *
+   * @param wmRuntimeInfo wireMock server on a random port
+   */
+  @Test
+  void testSonarAnalyzeCommand(WireMockRuntimeInfo wmRuntimeInfo) {
+
+    // arrange
+    IdeTestContext context = newContext(PROJECT_SONAR, wmRuntimeInfo);
```
Comment (hohwille) [inline cli/src/test/java/com/devonfw/tools/ide/tool/sonar/SonarTest.java]:
```suggestion
    IdeTestContext context = new IdeTestContext();
```

File: cli/src/test/java/com/devonfw/tools/ide/tool/sonar/SonarTest.java [hunk 3]
```diff
@@ -0,0 +1,210 @@
...
+    }
+  }
+
+  /**
+   * Tests that {@link Sonar#getBinaryName} returns correct values for different commands. This is a regression test for issue #1731 to ensure no NPE occurs
+   * when command is accessed.
+   *
+   * @param wmRuntimeInfo wireMock server on a random port
+   */
+  @Test
```
Comment (hohwille) [inline cli/src/test/java/com/devonfw/tools/ide/tool/sonar/SonarTest.java]: Also a good candidate for `@ParameterizedTest` to test all 3 operating systems.
