### PR TITLE
#587:  check for git installation

### LINKED ISSUE #587: IDEasy requires git but does not verify if git is installed
IDEasy has `git` as prerequisite.
Hence, it should check if `git` is installed and otherwise give a reasonable error message or even better suggest to download and install git.

```
C:\projects>ide create example
Creating new IDEasy project in C:\projects\_ide\example
Start: Clone settings repository
Missing your settings at C:\projects\_ide\example\settings and no SETTINGS_URL is defined.
Further details can be found here: https://github.com/devonfw/IDEasy/blob/main/documentation/settings.asciidoc
Please contact the technical lead of your project to get the SETTINGS_URL for your project.
In case you just want to test IDEasy you may simply hit return to install the default settings.
Settings URL [https://github.com/devonfw/ide-settings.git]:

Step 'Clone settings repository' ended with failure.
Step 'ide (create,example)' failed: java.lang.IllegalStateException: Running command 'git' with arguments 'clone' '--recursive' 'https://github.com/devonfw/ide-settings.git' '--config' 'core.autocrlf=false' '.' failed: Cannot run program "git" (in directory "C:\projects\_ide\example\settings"): CreateProcess error=2, The system cannot find the file specified
 Step 'Clone settings repository' failed: null
2 step(s) failed out of 2 steps.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/ide/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Running+command+%27git%27+with+arguments+%27clone%27+%27--recursive%27+%27https%3A%2F%2Fgithub.com%2Fdevonfw%2Fide-settings.git%27+%27--config%27+%27core.autocrlf%3Dfalse%27+%27.%27+failed%3A+Cannot+run+program+%22git%22+%28in+directory+%22C%3A%5Cprojects%5C_ide%5Cexample%5Csettings%22%29%3A+CreateProcess+error%3D2%2C+The+system+cannot+find+the+file+specified
java.lang.IllegalStateException: Running command 'git' with arguments 'clone' '--recursive' 'https://github.com/devonfw/ide-settings.git' '--config' 'core.autocrlf=false' '.' failed: Cannot run program "git" (in directory "C:\projects\_ide\example\settings"): CreateProcess error=2, The system cannot find the file specified
        at com.devonfw.tools.ide.process.ProcessContextImpl.run(ProcessContextImpl.java:173)
        at com.devonfw.tools.ide.context.GitContextImpl.clone(GitContextImpl.java:238)
        at com.devonfw.tools.ide.context.GitContextImpl.pullOrClone(GitContextImpl.java:194)
        at com.devonfw.tools.ide.context.GitContextImpl.pullOrClone(GitContextImpl.java:164)
        at com.devonfw.tools.ide.commandlet.AbstractUpdateCommandlet.updateSettings(AbstractUpdateCommandlet.java:128)
        at com.devonfw.tools.ide.commandlet.AbstractUpdateCommandlet.run(AbstractUpdateCommandlet.java:46)
        at com.devonfw.tools.ide.commandlet.CreateCommandlet.run(CreateCommandlet.java:61)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:867)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:779)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:89)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:29)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.io.IOException: Cannot run program "git" (in directory "C:\projects\_ide\example\settings"): CreateProcess error=2, The system cannot find the file specified
        at java.base@21.0.2/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
        at java.base@21.0.2/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
        at com.devonfw.tools.ide.process.ProcessContextImpl.run(ProcessContextImpl.java:147)
        ... 12 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:907)
        at java.base@21.0.2/java.lang.ProcessImpl.create(Native Method)
        at java.base@21.0.2/java.lang.ProcessImpl.<init>(ProcessImpl.java:500)
        at java.base@21.0.2/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base@21.0.2/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
        ... 14 more

You are not inside an IDE installation: C:\projects
IDE environment variables have been set for  in workspace
```

### PR DESCRIPTION
**Pull request by WorkingAmeise**
Closes #587 .

Added the isGitInstalled Method to GitContextImpl, that calls the findBash method of AbstractIdeContext and throws an IllegalstateException if there is no bash path found.
Used the newly added method at the start of every method that performs an action for which git is required.

### CODE REVIEW

**Review by jan-vcapgemini — APPROVED** [review]
LGTM. Ready for review.

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java [hunk 1]
```diff
@@ -292,6 +292,17 @@ IdeContext getContext() {
 
     return this.context;
   }
+
+  /**
+   * Checks if there is a git installation and throws an exception if there is none
+   */
+  private void isGitInstalled() {
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:299]: Please rename to `verifyGitInstalled()` or `ensureGitIsInstalled()`.
According to Java Bean conventions this is a (boolean) getter but getters do not have `void` as return type.

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java [hunk 2]
```diff
@@ -292,6 +292,17 @@ IdeContext getContext() {
...
+    if (this.context.findBash() == null) {
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:300]: This is a good check to do but it is not sufficient:
* the user could have bash globally installed but not from git-bash.
* the user may use Linux or MacOS where git is always pre-installed by the OS and `findBash` will not be `null`. Still the user may not have git installed.

So my suggestion would be to instead
* First just call `this.context.findBashRequired();`
* Then check if `git` is available as a binary executable. To do so you could simply use `this.context.getPath().findBinary(git)`  with `Path git = Path.of("git")`. In case you get the same (`==`) result back, then we do not have `git` on our PATH. Otherwise you will get the absolute `Path` back where the `git` executable binary is installed.

File: CHANGELOG.adoc [hunk 3]
```diff
@@ -12,7 +12,7 @@ The full list of changes for this release can be found in https://github.com/dev
 == 2024.11.001
 
 Release with new features and bugfixes:
-
+* https://github.com/devonfw/IDEasy/issues/587[#587]: Checks for git installation before performing git operations
```
Comment (hohwille) [inline CHANGELOG.adoc:15]: `2024.11.001` is already released.
You need to move this up to `2024.12.001`.
This time we should be able to include it into that release and not miss it again.

**Review by hohwille — APPROVED** [review]
@WorkingAmeise thanks for your PR. You added the git verification before every git execution in `GitContextImpl` what seems perfectly correct. 👍 
For the check itself, I left some comments for rework and improvement.
After all review-comments are addressed, we can merge.
Thanks!

File: CHANGELOG.adoc (hunk 3 above)
Comment (WorkingAmeise) [reply CHANGELOG.adoc]: Moved this to the right release

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java [hunk 4]
```diff
@@ -292,6 +292,20 @@ IdeContext getContext() {
...
   }
+
+  /**
+   * Checks if there is a git installation and throws an exception if there is none
+   */
+  private void verifyGitInstalled() {
+    String requiredBash = this.context.findBashRequired();
+    Path git = Path.of("git");
+    String binaryGitPath = this.context.getPath().findBinary(git).toString();
+    if (requiredBash == binaryGitPath) {
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java:303]: Here you mixed two different checks:
1. verify that we have a bash. You do not need to assign the result of `this.context.findBashRequired()` to a variable since we only want to ensure that bash is available. Otherwise this method will throw an exception.
2. we want to check that git is installed, therefore you need to check `if (git == binaryGitPath) {`

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java (hunk 2 above)
Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java]: Please check my new review comment to see the misunderstanding.

File: cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java (hunk 4 above)
Comment (WorkingAmeise) [reply cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java]: Seperated

Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java]: @WorkingAmeise thanks for your update. Now perfect 👍

**Comment by hohwille** [comment]
For the record: Throws `InvalidArgumentException` instead of `CliException` and therefore printing a stacktrace with link to create github issue what is undesired. We need to create a new story and PR changing the exception type. Everything else works fine.
