### PR TITLE
#1340: proper fix if IDE_ROOT is not sane

### LINKED ISSUE #1340: IDE_ROOT case can be overwritten
### Actual behavior

As an IDEasy user I expect that `IDE_ROOT` always gets used properly.
If I've installed my IDEasy to `D:\projects` and I'm running it using a different user.dir e.g. `D:\Projects` IDEasy will report some strange error messages:
`Undefined edition null of tool intellij`
as well as create faulty plugin marker files like: `plugin.eclipse.null.checkstyle`.

### Reproduce

1. Adjust your Windows Terminal Start directory to use your IDE_ROOT in uppercase (your actual IDE_ROOT needs to be in lower case)
Image
2. Create a test project e.g.` ide create test -`
3. Switch to your test project e.g. `icd -p test`
2. Delete plugin marker files of intellij from `$IDE_ROOT/test/.ide` folder
3. Run `ide -d intellij`

### Expected behavior

IDEasy should not report these messages and create proper plugin marker files.

### IDEasy status

```bash
Updates are available for the settings repository. If you want to apply the latest changes, call "ide update"
IDE_ROOT is set to D:\Projects
IDE_HOME is set to D:\Projects\ideasy-dev
You are online.
Your settings are not up-to-date, please run 'ide update'.
Your version of IDEasy is 2025.05.002-SNAPSHOT but version 2025.05.002-20250524.024139-3 is available. Please run the following command to upgrade to the latest version:
ide upgrade
Your operating system is windows(10.0)@x64 [Windows 10@amd64]
Successfully completed ide (status)
```

### Related/Dependent issues

_No response_

### Comments/Hints

This seems to be related to this method: https://github.com/devonfw/IDEasy/blob/f36571941daa6ee0afe8fd5fca19406c82338655/cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java#L357-L371
which will return `null` if the path did not match.

### PR DESCRIPTION
**Pull request by hohwille**
### Implemented changes:

* Log warning if IDE_ROOT is not sane (undefined, wrong case, not matching parent of IDE_HOME)
* Auto-repair IDE_ROOT if not sane to prevent follow up errors.

---

## Checklist for this PR

Make sure everything is checked before merging this PR. For further info please also see
our [DoD](https://github.com/devonfw/IDEasy/blob/main/documentation/DoD.adoc).

- [x] When running `mvn clean test` locally all tests pass and build is successful
- [x] PR title is of the form `#«issue-id»: «brief summary»` (e.g. `#921: fixed setup.bat`). If no issue ID exists, title only.
- [x] PR top-level comment summarizes what has been done and contains link to addressed issue(s)
- [x] PR and issue(s) have suitable labels
- [x] Issue is set to `In Progress` and assigned to you *or* there is no issue (might happen for very small PRs)
- [x] You followed all [coding conventions](https://github.com/devonfw/IDEasy/blob/main/documentation/coding-conventions.adoc)
- [x] You have added the issue implemented by your PR in [CHANGELOG.adoc](https://github.com/devonfw/IDEasy/blob/main/CHANGELOG.adoc) unless issue is labeled
  with `internal`

### CODE REVIEW

File: cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java [hunk 1]
```diff
@@ -208,23 +207,50 @@ private Path findIdeRoot(Path ideHomePath) {
 
     Path ideRootPath = null;
     if (ideHomePath != null) {
+      Path ideRootPathFromEnv = getIdeRootPathFromEnv(true);
       ideRootPath = ideHomePath.getParent();
+      if ((ideRootPathFromEnv != null) && !ideRootPath.toString().equals(ideRootPathFromEnv.toString())) {
+        warning("Variable IDE_ROOT is set to '{}' but for your project '{}' the path '{}' would have been expected.", ideRootPathFromEnv,
+            ideHomePath.getFileName(), ideRootPath);
```
Comment (jan-vcapgemini) [inline cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java:214]:
```suggestion
        warning("Variable IDE_ROOT is set to '{}' but for your project '{}' the path '{}' would have been expected.", ideRootPathFromEnv,
            ideRootPath, ideHomePath.getFileName());
```

**Review by jan-vcapgemini — COMMENTED** [review]
@hohwille thanks for providing a fix for this issue. I've tested your changes but still got the warning messages: `Undefined edition null of tool intellij`. It looks like the automatic repair is not working yet.

**Comment by jan-vcapgemini** [comment]
@hohwille please apply the same fix for the `CWD` then the original bug should be fixed.

**Review by jan-vcapgemini — APPROVED** [review]
@hohwille looks like your last change fixed the original issue now. I've tested your changes with a local graalvm image and it worked fine. Can be merged now.
