### PR TITLE
#1786: Fix rate limits GitHub API

### LINKED ISSUE #1786: Rate-limits from GitHub for GitHubActions prevent finding updates
### Actual behavior

Our Update URLs workflow could not update maven because of this error:
```
15:21:23.646 [com.devonfw.tools.ide.url.UpdateInitiator.main()] - ERROR - c.d.t.ide.url.updater.UpdateManager - Failed to update mvn
java.lang.IllegalStateException: Error while getting versions from JSON API https://api.github.com/repos/apache/maven/releases
	at com.devonfw.tools.ide.url.updater.JsonUrlUpdater.update(JsonUrlUpdater.java:54)
	at com.devonfw.tools.ide.url.updater.UpdateManager.update(UpdateManager.java:133)
	at com.devonfw.tools.ide.url.updater.UpdateManager.updateAll(UpdateManager.java:108)
	at com.devonfw.tools.ide.url.UpdateInitiator.main(UpdateInitiator.java:65)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalStateException: Failed to retrieve response body from url: https://api.github.com/repos/apache/maven/releases
	at com.devonfw.tools.ide.url.updater.AbstractUrlUpdater.doGetResponseBodyAsString(AbstractUrlUpdater.java:176)
	at com.devonfw.tools.ide.url.updater.JsonUrlUpdater.update(JsonUrlUpdater.java:42)
	... 5 common frames omitted
Caused by: java.lang.IllegalStateException: Unexpected response code 403:{"message":"API rate limit exceeded for 172.190.93.131. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

	at com.devonfw.tools.ide.url.updater.AbstractUrlUpdater.doGetResponseBodyAsString(AbstractUrlUpdater.java:174)
	... 6 common frames omitted
```

### Reproduce

See Logs of "Update URLs" GitHub action workflow.

### Expected behavior

New maven versions should be found via the REST API.

### IDEasy status

```bash
n.a.
```

### Related/Dependent issues

#1771

### Comments/Hints

https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting

Maybe from GitHub action we get a token out of the box that we can pass to our URL updater process.
Otherwise we can create an account and configure the credentials as GitHub secrets.

### PR DESCRIPTION
**Pull request by jakozian**
### Implemented changes:

* Added env variable to the UrlUpdater to send token in every GitHub API request.
* Added env variable to update-urls workflow.

---

## Checklist for this PR

Make sure everything is checked before merging this PR. For further info please also see
our [DoD](https://github.com/devonfw/IDEasy/blob/main/documentation/contributing/DoD.adoc).

- [x] When running `mvn clean test` locally all tests pass and build is successful
- [x] PR title is of the form `#«issue-id»: «brief summary»` (e.g. `#921: fixed setup.bat`). If no issue ID exists, title only.
- [x] PR top-level comment summarizes what has been done and contains link to addressed issue(s)
- [x] PR and issue(s) have suitable labels
- [x] Issue is set to `In Progress` and assigned to you *or* there is no issue (might happen for very small PRs)
- [x] You followed all [coding conventions](https://github.com/devonfw/IDEasy/blob/main/documentation/coding-conventions.adoc)
- [x] You have added the issue implemented by your PR in [CHANGELOG.adoc](https://github.com/devonfw/IDEasy/blob/main/CHANGELOG.adoc) unless issue is labeled
  with `internal`

### CODE REVIEW

**Review by ducminh02 — APPROVED** [review]
cool, nice fix!

File: url-updater/src/main/java/com/devonfw/tools/ide/url/updater/AbstractUrlUpdater.java [hunk 1]
```diff
@@ -506,8 +529,7 @@ protected HttpResponse<?> doCheckDownloadViaHeadRequest(String url) {
     HttpRequest request = null;
     try {
       uri = URI.create(url);
```
Comment (hohwille) [inline url-updater/src/main/java/com/devonfw/tools/ide/url/updater/AbstractUrlUpdater.java]: This variable is now unused and URI.create is called twice. This one is pointless. Please remove:

```suggestion
```

**Review by hohwille — APPROVED** [review]
@jakozian thanks for your PR. Looks all good to me. I double-checked that the `GHA_TOKEN` already exists as secret for our actions. 👍 
Ready for merge.

**Comment by hohwille** [comment]
noting broke and the error did not show up again.
But hard to test in reality. I will simply set QA label.
