### PR TITLE
#1053: fix setup #1044: setup rewritten in Java

### LINKED ISSUE #1044: Reimplement setup scripts in Java
From all we learned CMD is the worst "programming language" we have included and compared to Java it is followed by bash.
That means we should implement as little as possible in shell scripts and as much as possible in Java.
This leads to the following idea of this story:

We extend `InstallCommandlet` with the following ability:
* If no tool is provided (`ideasy install` is invoked and not `ideasy install «tool»`), then we trigger Java functionality to do the installation of IDEasy.
* A special challenge of this is that we do not have IDE_HOME and various initializations will not work (IDE_ROOT may be undefined, etc.). Currently `InstallCommandlet` has `isIdeHomeRequired() == true` what would need to be changed, while this is still required if a `«tool»` argument is defined.
* The required implementation steps can be found in the current `setup` and `setup.bat` scripts:
  * Determine IDE_ROOT, via env variable.
  * If undefined check if we are on Linux/Mac or if we are inside the users home directory, then we set `IDE_ROOT=~/projects`
  * Otherwise set `IDE_ROOT=/«drive-letter»/projects`
  * Copy the installation to `$IDE_ROOT/_ide/software/maven/ideasy/ideasy/«current-version»`
  * Create a link to that copied installation under `$IDE_ROOT/_ide/installation`
  * Tweak `.bashrc` and `.zshrc` to ensure `functions` are sourced from there.
  * if `IDE_ROOT` was newly defined, set it as user env var on Windows or via `.bashrc` and `.zshrc` on other platforms
  * On Windows put `$IDE_ROOT/_ide/installation/bin` to the PATH
  * On Windows all PATH entries in user env vars need to be in Windows syntax.
  * The installation process must be idempotent, so repeating it multiple times does not cause duplicated entires in PATH, variables, `.bashrc`, etc. and also do not override existing installation in software repo.
* Adapt the `setup` and `setup.bat` scripts:
  * `setup.bat` will only call setup and do nothing else (remove PATH modifications, etc.), keep the `pause` call if not in batch mode.
  * `setup` will only call `ideasy install` and nothing else.

### LINKED ISSUE #1053: New setup script is adding incomplete path to PATH user environment variable on Windows
After running `setup.bat` I get this in my environment variables:

Image

This seems to be a bug introduced by PR #1021

### PR DESCRIPTION
**Pull request by hohwille**
Fixes #1053 fixes #1044

* rewritten setup in Java (in `IdeasyCommandlet`)
* triggered via `ideasy -f install`
* reduced `setup` bash script to run that
* reduced `setup.bat` to find bash and run `setup`
* emptied migration and solved all in the setup directly
* added `IdeasyCommandletTest`

### CODE REVIEW

File: cli/src/main/java/com/devonfw/tools/ide/tool/IdeasyCommandlet.java [hunk 1]
```diff
@@ -108,4 +133,188 @@ public boolean checkIfUpdateIsAvailable() {
...
+        this.context.error("Could not read user PATH from registry!");
+      } else {
+        this.context.info("Found user PATH={}", userPath);
+        Path ideasyBinPath = installationPath.resolve("bin");
+        userPath = removeObsoleteEntryFromWindowsPath(userPath);
+        if (userPath.isEmpty()) {
+          this.context.warning("ATTENTION:\n"
+              + "Your user specific PATH variable seems to be empty.\n"
+              + "You can double check this by pressing [Windows][r] and launch the program SystemPropertiesAdvanced.\n"
+              + "Then click on 'Environment variables' and check if 'PATH' is set in in the 'user variables' from the upper list.\n"
```
Comment (jan-vcapgemini) [inline cli/src/main/java/com/devonfw/tools/ide/tool/IdeasyCommandlet.java:193]:
```suggestion
              + "Then click on 'Environment variables' and check if 'PATH' is set in the 'user variables' from the upper list.\n"
```

File: cli/src/main/java/com/devonfw/tools/ide/tool/IdeasyCommandlet.java [hunk 2]
```diff
@@ -108,4 +133,188 @@ public boolean checkIfUpdateIsAvailable() {
       return true;
     }
   }
+
+  /**
+   * Initial installation of IDEasy.
+   *
+   * @see com.devonfw.tools.ide.commandlet.InstallCommandlet
+   */
+  public void installIdeasy(Path cwd) {
```
Comment (jan-vcapgemini) [inline cli/src/main/java/com/devonfw/tools/ide/tool/IdeasyCommandlet.java:142]: `cwd` missing in Javadoc.

File: cli/src/main/java/com/devonfw/tools/ide/tool/IdeasyCommandlet.java [hunk 3]
```diff
@@ -108,4 +133,188 @@ public boolean checkIfUpdateIsAvailable() {
...
+      Path installRoot = home;
+      if (this.context.getSystemInfo().isWindows()) {
+        if (!cwd.startsWith(home)) {
+          installRoot = cwd.getRoot();
+        }
+      }
+      ideRoot = installRoot.resolve(IdeContext.FOLDER_PROJECTS);
+    } else {
+      assert (Files.isDirectory(ideRoot)) : "IDE_ROOT directory does not exist!";
+      // assert (ideRoot.getFileName().toString().equals(IdeContext.FOLDER_PROJECTS)) : "IDE_ROOT should point to projects folder!";
```
Comment (jan-vcapgemini) [inline cli/src/main/java/com/devonfw/tools/ide/tool/IdeasyCommandlet.java:315]:
```suggestion
```

File: cli/src/main/java/com/devonfw/tools/ide/tool/IdeasyCommandlet.java (hunk 2 above)
Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/tool/IdeasyCommandlet.java:143]: Done.

**Review by jan-vcapgemini — COMMENTED** [review]
LGTM. Still need to test this locally. Will approve afterwards.

**Review by jan-vcapgemini — APPROVED** [review]
Ready for merge.

**Comment by hj-lorenz** [comment]
Further test ducumentation:
[Testresults-install-PR#1055-bugs#1054-und-bug#1044.txt](https://github.com/user-attachments/files/18892413/Testresults-install-PR.1055-bugs.1054-und-bug.1044.txt)
