### PR TITLE
#1405: Fix integration test order dependency

### LINKED ISSUE #1405: integration tests fail if executed in specific order
### Actual behavior

When verify-longpaths.sh is executed before install-intellij.sh, install-intellij.sh fails.

### Reproduce

Rename verify-longpaths.sh to ensure-longpaths.sh, so that it's executed first. Then execute the integration tests.

### Expected behavior

All integration tests should succeed.

### IDEasy status

```bash
Updates are available for the settings repository. If you want to apply the latest changes, call "ide update"
IDE_ROOT is set to D:\projects
IDE_HOME is set to D:\projects\IDEasy
You are online.
Your settings are not up-to-date, please run 'ide update'.
Your version of IDEasy is 2025.06.002-SNAPSHOT but version 2025.07.001-20250628.024352-1 is available. Please run the following command to upgrade to the latest version:
ide upgrade
Your operating system is windows(10.0)@x64 [Windows 11@amd64]
Successfully completed ide (status)
```

### Related/Dependent issues

_No response_

### Comments/Hints

_No response_

### PR DESCRIPTION
**Pull request by maybeec**
### This PR fixes #1405

This PR addresses the issue where integration tests were failing when executed in alphabetical order due to environment interference between tests.

### Root Cause

The original issue occurred when `verify-longpaths.sh` was renamed to `ensure-longpaths.sh`, causing it to run first alphabetically. The test used `$IDE -f install` which performs a forced full IDEasy installation that modifies the global environment and interferes with subsequent tests. The `install-intellij.sh` test expected a clean environment for tool-specific installation.

### Implemented changes:

* **Improved OS detection**: Added `doGetOsType()` function to detect OS type based on `$OSTYPE` instead of relying on GitHub workflow matrix variables (`MATRIX_OS`). This makes tests more portable and runnable outside GitHub Actions.
* **Updated test infrastructure**: Modified `doDownloadSnapshot()`, `doIsMacOs()`, and `doIsWindows()` functions to use the new OS detection method.
* **Test isolation improvements**: Added environment backup/restore mechanism in `all-tests.sh`:
  - Backs up and restores `IDE_ROOT` and `PATH` environment variables
  - Backs up and restores shell RC files (`.bashrc`, `.zshrc`) to prevent user configuration corruption
  - Resets test variables between each test execution using `doResetVariables()`
  - Added trap to ensure cleanup happens even on errors
* **Improved error handling**: Made the upgrade process more robust by continuing with downloaded version if upgrade fails
* **Better function file detection**: Added fallback logic to locate the functions file in both installation path and root directory
* **New integration test**: Added `force-install.sh` test to reproduce and validate the environment interference issue

These changes ensure that all integration tests succeed regardless of execution order, maintaining proper test independence.

---

## Checklist for this PR

Make sure everything is checked before merging this PR. For further info please also see
our [DoD](https://github.com/devonfw/IDEasy/blob/main/documentation/DoD.adoc).

- [x] When running `mvn clean test` locally all tests pass and build is successful
- [x] PR title is of the form `#«issue-id»: «brief summary»` (e.g. `#921: fixed setup.bat`). If no issue ID exists, title only.
- [x] PR top-level comment summarizes what has been done and contains link to addressed issue(s)
- [x] PR and issue(s) have suitable labels
- [x] Issue is set to `In Progress` and assigned to you *or* there is no issue (might happen for very small PRs)
- [x] You followed all [coding conventions](https://github.com/devonfw/IDEasy/blob/main/documentation/coding-conventions.adoc)
- [x] You have added the issue implemented by your PR in [CHANGELOG.adoc](https://github.com/devonfw/IDEasy/blob/main/CHANGELOG.adoc) unless issue is labeled
  with `internal`

---

**Note**: This PR replaces #1417 which was created by copilot-swe-agent. Due to CLA assistant issues with copilot-authored commits, the changes have been manually recreated with proper authorship attribution.

### CODE REVIEW

File: cli/src/test/all-tests-functions.sh [hunk 1]
```diff
@@ -43,22 +43,40 @@ function doDownloadSnapshot () {
...
     curl -o "${IDEASY_COMPRESSED_FILE:?}" "$url"
     rm "${pageHtmlLocal:?}"
   fi
 }
 
+function doGetOsType() {
+  local osType
+  case "$OSTYPE" in
+    msys*|cygwin*|win32*)
+      osType="windows-x64"
```
Comment (hohwille) [inline cli/src/test/all-tests-functions.sh]: This is actually wrong. I tested this on Windows@ARM64 and it gives me `windows-x64`.
However, the architecture does not seem to matter in any of our integration tests.
IMHO this is somehow coming from the replaced `MATRIX_OS`.
I would suggest that we simply remove the architecture since the method names are only about the operating system: `doGetOsType`, `doIsWindows`, `doIsMacOs`.
If we later need a separation by architecture, we can add another function for that.

Comment (hohwille) [reply cli/src/test/all-tests-functions.sh]: I created issue #1665 for this topic.
I therefore resolve this now so we can merge this PR and address that issue later.
