### PR TITLE
#1511: Fixed npm commands

### LINKED ISSUE #1511: Npm does not install packages in our software folder
### Actual behavior

When running npm install -g @angular/cli, npm will install the package in a global location defined by prefix.
This is fatal if we want to isolate node from other npm installations.

### Reproduce

1. Pre-install node in a regular location
2. install npm
3. try to install a package
4. check f.e. -d ng --version

### Expected behavior

IDEasy should always use our node installation for npm packages.

### IDEasy status

```bash
IDE_ROOT is set to ~/projects
IDE_HOME is set to ~/projects/project
You are online.
Your settings are not up-to-date, please run 'ide update'.
Your version of IDEasy is 2025.09.001-SNAPSHOT.
You are using a SNAPSHOT version of IDEasy. For stability consider switching to a stable release via 'ide upgrade --mode=stable'
Your version of IDEasy is 2025.09.001-SNAPSHOT but version 2025.07.001-20250723.025205-3 is available. Please run the following command to upgrade to the latest version:
ide upgrade
Your operating system is linux(5.15.167.4-microsoft-standard-WSL2)@x64 [Linux@amd64]
Successfully completed ide (status)
```

### Related/Dependent issues

_No response_

### Comments/Hints

_No response_

### PR DESCRIPTION
**Pull request by jan-vcapgemini**
### Implemented changes:

* added prefix param to package installation, list and uninstall commands with path to current node installation
* added new StringUtil class with extendArray method
* added unit tests for StringUtil class (generated by Copilot)

---

## Checklist for this PR

Make sure everything is checked before merging this PR. For further info please also see
our [DoD](https://github.com/devonfw/IDEasy/blob/main/documentation/DoD.adoc).

- [x] When running `mvn clean test` locally all tests pass and build is successful
- [x] PR title is of the form `#«issue-id»: «brief summary»` (e.g. `#921: fixed setup.bat`). If no issue ID exists, title only.
- [x] PR top-level comment summarizes what has been done and contains link to addressed issue(s)
- [x] PR and issue(s) have suitable labels
- [x] Issue is set to `In Progress` and assigned to you *or* there is no issue (might happen for very small PRs)
- [x] You followed all [coding conventions](https://github.com/devonfw/IDEasy/blob/main/documentation/coding-conventions.adoc)
- [x] You have added the issue implemented by your PR in [CHANGELOG.adoc](https://github.com/devonfw/IDEasy/blob/main/CHANGELOG.adoc) unless issue is labeled
  with `internal`

### CODE REVIEW

File: cli/src/main/java/com/devonfw/tools/ide/tool/npm/NpmBasedCommandlet.java [hunk 1]
```diff
@@ -54,7 +54,8 @@ protected VersionIdentifier runPackageManagerGetInstalledVersion(String npmPacka
       this.context.trace("Since node is not installed, also package {} for tool {} cannot be installed.", npmPackage, this.tool);
       return null;
     }
-    ProcessResult result = runPackageManager(ProcessMode.DEFAULT_CAPTURE, ProcessErrorHandling.NONE, "list", "-g", npmPackage, "--depth=0");
+    ProcessResult result = runPackageManager(ProcessMode.DEFAULT_CAPTURE, ProcessErrorHandling.NONE, "list", "-g", npmPackage, "--depth=0", "--prefix",
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/tool/npm/NpmBasedCommandlet.java:57]: If we always need to add `--prefix` you should add it centrally in `runPackageManager` to avoid redundancies.

**Review by hohwille — APPROVED** [review]
Fine. This should make the global installation robust even in odd situations where multiple node.js installations exists on the same computer and are all visible in PATH and env variables. 👍

File: cli/src/main/java/com/devonfw/tools/ide/tool/npm/NpmBasedCommandlet.java (hunk 1 above)
Comment (jan-vcapgemini) [reply cli/src/main/java/com/devonfw/tools/ide/tool/npm/NpmBasedCommandlet.java]: I've removed the redundancies now and added a new StringUtil method for this case.

File: cli/src/main/java/com/devonfw/tools/ide/util/StringUtil.java [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+        System.arraycopy(args, 0, out, eLen, aLen);
+      }
+    } else {
+      // [args..., extraArgs...]
+      if (aLen > 0) {
+        System.arraycopy(args, 0, out, 0, aLen);
+      }
+      if (eLen > 0) {
+        System.arraycopy(extraArgs, 0, out, aLen, eLen);
+      }
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/util/StringUtil.java:44]: simplify:
```suggestion
      System.arraycopy(extraArgs, 0, out, 0, eLen);
      System.arraycopy(args, 0, out, eLen, aLen);
    } else {
      // [args..., extraArgs...]
      System.arraycopy(args, 0, out, 0, aLen);
      System.arraycopy(extraArgs, 0, out, aLen, eLen);
```

**Review by hohwille — APPROVED** [review]
@jan-vcapgemini thanks for the update and also the test of the new functionality 👍

File: cli/src/test/java/com/devonfw/tools/ide/util/StringUtilTest.java [hunk 3]
```diff
@@ -0,0 +1,317 @@
...
+  void testExtraNullPrependReturnsCopyOfArgs() {
+    // given
+    String[] args = { "run", "test" };
+
+    // when
+    String[] actual = StringUtil.extendArray(args, true, (String[]) null);
+
+    // then
+    assertThat(actual).containsExactly("run", "test");
+    assertThat(actual).isNotSameAs(args);
```
Comment (hohwille) [inline cli/src/test/java/com/devonfw/tools/ide/util/StringUtilTest.java:134]: and here
```suggestion
```

File: cli/src/test/java/com/devonfw/tools/ide/util/StringUtilTest.java [hunk 4]
```diff
@@ -0,0 +1,317 @@
...
+  void testNoExtraPrependReturnsCopyOfArgs() {
+    // given
+    String[] args = { "x", "y" };
+
+    // when
+    String[] actual = StringUtil.extendArray(args, true);
+
+    // then
+    assertThat(actual).containsExactly("x", "y");
+    assertThat(actual).isNotSameAs(args);
```
Comment (hohwille) [inline cli/src/test/java/com/devonfw/tools/ide/util/StringUtilTest.java:300]: and finally here
```suggestion
```
